// AUTO-GENERATED DATA — do not edit manually
// ignore_for_file: lines_longer_than_80_chars, prefer_single_quotes

import 'models.dart';

final Map<int, List<KanjiItem>> kanjiData = {
  1: [
    KanjiItem(kanji:"一",reading:"Ichi",meaning:"এক",on:"イチ",kun:"ひと(つ)"),
    KanjiItem(kanji:"二",reading:"Ni",meaning:"দুই",on:"ニ",kun:"ふた(つ)"),
    KanjiItem(kanji:"三",reading:"San",meaning:"তিন",on:"サン",kun:"みっ(つ)"),
    KanjiItem(kanji:"四",reading:"Shi / Yon",meaning:"চার",on:"シ",kun:"よっ(つ)"),
    KanjiItem(kanji:"五",reading:"Go",meaning:"পাঁচ",on:"ゴ",kun:"いつ(つ)"),
  ],
  2: [
    KanjiItem(kanji:"六",reading:"Roku",meaning:"ছয়",on:"ロク",kun:"むっ(つ)"),
    KanjiItem(kanji:"七",reading:"Shichi / Nana",meaning:"সাত",on:"シチ",kun:"なな(つ)"),
    KanjiItem(kanji:"八",reading:"Hachi",meaning:"আট",on:"ハチ",kun:"やっ(つ)"),
    KanjiItem(kanji:"九",reading:"Kyuu / Ku",meaning:"নয়",on:"キュウ, ク",kun:"ここの(つ)"),
    KanjiItem(kanji:"十",reading:"Juu",meaning:"দশ",on:"ジュウ",kun:"とお"),
  ],
  3: [
    KanjiItem(kanji:"百",reading:"Hyaku",meaning:"এক শত",on:"ヒャク",kun:"—"),
    KanjiItem(kanji:"千",reading:"Sen",meaning:"হাজার",on:"セン",kun:"—"),
    KanjiItem(kanji:"万",reading:"Man",meaning:"দশ হাজার",on:"マン",kun:"—"),
    KanjiItem(kanji:"円",reading:"En",meaning:"ইয়েন / বৃত্ত",on:"エン",kun:"まる"),
    KanjiItem(kanji:"口",reading:"Kou, Ku",meaning:"মুখ",on:"コウ, ク",kun:"くち"),
  ],
  4: [
    KanjiItem(kanji:"目",reading:"Moku",meaning:"চোখ",on:"モク",kun:"め"),
    KanjiItem(kanji:"耳",reading:"Ji",meaning:"কান",on:"ジ",kun:"みみ"),
    KanjiItem(kanji:"手",reading:"Shu",meaning:"হাত",on:"シュ",kun:"て"),
    KanjiItem(kanji:"足",reading:"Soku",meaning:"পা",on:"ソク",kun:"あし"),
    KanjiItem(kanji:"力",reading:"Ryoku",meaning:"শক্তি",on:"リョク",kun:"ちから"),
  ],
  5: [
    KanjiItem(kanji:"男",reading:"Dan",meaning:"পুরুষ",on:"ダン",kun:"おとこ"),
    KanjiItem(kanji:"女",reading:"Jo",meaning:"নারী",on:"ジョ",kun:"おんな"),
    KanjiItem(kanji:"子",reading:"Shi",meaning:"শিশু",on:"シ",kun:"こ"),
    KanjiItem(kanji:"父",reading:"Fu",meaning:"বাবা",on:"フ",kun:"ちち"),
    KanjiItem(kanji:"母",reading:"Bo",meaning:"মা",on:"ボ",kun:"はは"),
  ],
  6: [
    KanjiItem(kanji:"人",reading:"Jin, Nin",meaning:"মানুষ",on:"ジン, ニン",kun:"ひと"),
    KanjiItem(kanji:"友",reading:"Yuu",meaning:"বন্ধু",on:"ユウ",kun:"とも"),
    KanjiItem(kanji:"名",reading:"Mei",meaning:"নাম",on:"メイ",kun:"な"),
    KanjiItem(kanji:"日",reading:"Nichi",meaning:"দিন / সূর্য",on:"ニチ, ジツ",kun:"ひ, か"),
    KanjiItem(kanji:"月",reading:"Getsu",meaning:"চাঁদ / মাস",on:"ゲツ, ガツ",kun:"つき"),
  ],
  7: [
    KanjiItem(kanji:"火",reading:"Ka",meaning:"আগুন",on:"カ",kun:"ひ"),
    KanjiItem(kanji:"水",reading:"Sui",meaning:"পানি",on:"スイ",kun:"みず"),
    KanjiItem(kanji:"木",reading:"Moku",meaning:"গাছ",on:"モク, ボク",kun:"き"),
    KanjiItem(kanji:"金",reading:"Kin",meaning:"টাকা / সোনা",on:"キン, コン",kun:"かね"),
    KanjiItem(kanji:"土",reading:"Do",meaning:"মাটি",on:"ド, ト",kun:"つち"),
  ],
  8: [
    KanjiItem(kanji:"山",reading:"San",meaning:"পাহাড়",on:"サン",kun:"やま"),
    KanjiItem(kanji:"川",reading:"Sen",meaning:"নদী",on:"セン",kun:"かわ"),
    KanjiItem(kanji:"田",reading:"Den",meaning:"ধানক্ষেত",on:"デン",kun:"た"),
    KanjiItem(kanji:"天",reading:"Ten",meaning:"আকাশ / স্বর্গ",on:"テン",kun:"—"),
    KanjiItem(kanji:"気",reading:"Ki",meaning:"উৎসাহ / বাতাস",on:"キ",kun:"—"),
  ],
  9: [
    KanjiItem(kanji:"空",reading:"Kuu",meaning:"আকাশ",on:"クウ",kun:"そら"),
    KanjiItem(kanji:"雨",reading:"U",meaning:"বৃষ্টি",on:"ウ",kun:"あめ"),
    KanjiItem(kanji:"電",reading:"Den",meaning:"বিদ্যুৎ",on:"デン",kun:"—"),
    KanjiItem(kanji:"車",reading:"Sha",meaning:"গাড়ি",on:"シャ",kun:"くるま"),
    KanjiItem(kanji:"校",reading:"Kou",meaning:"স্কুল",on:"コウ",kun:"—"),
  ],
  10: [
    KanjiItem(kanji:"学",reading:"Gaku",meaning:"অধ্যয়ন",on:"ガク",kun:"まな(ぶ)"),
    KanjiItem(kanji:"生",reading:"Sei",meaning:"জীবন",on:"セイ, ショウ",kun:"い(きる)"),
    KanjiItem(kanji:"先",reading:"Sen",meaning:"আগে",on:"セン",kun:"さき"),
    KanjiItem(kanji:"何",reading:"Ka",meaning:"কি",on:"カ",kun:"なに, なん"),
  ],
  11: [
    KanjiItem(kanji:"時",reading:"Toki",meaning:"সময়",on:"ジ",kun:"とき"),
    KanjiItem(kanji:"間",reading:"Aida",meaning:"মধ্যে",on:"カン",kun:"あいだ"),
    KanjiItem(kanji:"今",reading:"Ima",meaning:"এখন",on:"コン",kun:"いま"),
    KanjiItem(kanji:"週",reading:"Shuu",meaning:"সপ্তাহ",on:"シュウ",kun:"—"),
    KanjiItem(kanji:"年",reading:"Toshi",meaning:"বছর",on:"ネン",kun:"とし"),
  ],
  12: [
    KanjiItem(kanji:"午",reading:"Go",meaning:"মধ্যাহ্ন",on:"ゴ",kun:"—"),
    KanjiItem(kanji:"前",reading:"Mae",meaning:"আগে",on:"ゼン",kun:"まえ"),
    KanjiItem(kanji:"後",reading:"Ato",meaning:"পরে",on:"ゴ, コウ",kun:"うしろ, あと"),
    KanjiItem(kanji:"毎",reading:"Mai",meaning:"প্রতিটি",on:"マイ",kun:"—"),
    KanjiItem(kanji:"高",reading:"Takai",meaning:"উচ্চ / দামী",on:"コウ",kun:"たか(い)"),
  ],
  13: [
    KanjiItem(kanji:"安",reading:"Yasui",meaning:"সস্তা",on:"アン",kun:"やす(い)"),
    KanjiItem(kanji:"新",reading:"Atarashii",meaning:"নতুন",on:"シン",kun:"あたら(しい)"),
    KanjiItem(kanji:"古",reading:"Furui",meaning:"পুরনো",on:"コ",kun:"ふる(い)"),
    KanjiItem(kanji:"長",reading:"Nagai",meaning:"লম্বা",on:"チョウ",kun:"なが(い)"),
    KanjiItem(kanji:"多",reading:"Ooi",meaning:"অনেক",on:"タ",kun:"おお(い)"),
  ],
  14: [
    KanjiItem(kanji:"少",reading:"Sukunai",meaning:"অল্প",on:"ショウ",kun:"すく(ない)"),
    KanjiItem(kanji:"白",reading:"Shiro",meaning:"সাদা",on:"ハク",kun:"しろ(い)"),
    KanjiItem(kanji:"黒",reading:"Kuro",meaning:"কালো",on:"コク",kun:"くろ(い)"),
    KanjiItem(kanji:"赤",reading:"Aka",meaning:"লাল",on:"セキ",kun:"あか(い)"),
    KanjiItem(kanji:"青",reading:"Ao",meaning:"নীল",on:"セイ",kun:"あお(い)"),
  ],
  15: [
    KanjiItem(kanji:"色",reading:"Iro",meaning:"রং",on:"ショク",kun:"いろ"),
    KanjiItem(kanji:"書",reading:"Kaku",meaning:"লিখা",on:"ショ",kun:"か(く)"),
    KanjiItem(kanji:"聞",reading:"Kiku",meaning:"শোনা / জিজ্ঞেস করা",on:"ブン, モン",kun:"き(く)"),
    KanjiItem(kanji:"話",reading:"Hanasu",meaning:"বলা",on:"ワ",kun:"はな(す)"),
    KanjiItem(kanji:"言",reading:"Iu",meaning:"বলা",on:"ゲン, ゴン",kun:"い(う)"),
  ],
  16: [
    KanjiItem(kanji:"読",reading:"Yomu",meaning:"পড়া",on:"ドク",kun:"よ(む)"),
    KanjiItem(kanji:"見",reading:"Miru",meaning:"দেখা",on:"ケン",kun:"み(る)"),
    KanjiItem(kanji:"行",reading:"Iku",meaning:"যাওয়া",on:"コウ, ギョウ",kun:"い(く)"),
    KanjiItem(kanji:"来",reading:"Kuru",meaning:"আসা",on:"ライ",kun:"く(る)"),
    KanjiItem(kanji:"帰",reading:"Kaeru",meaning:"ফিরে আসা",on:"キ",kun:"かえ(る)"),
  ],
  17: [
    KanjiItem(kanji:"食",reading:"Taberu",meaning:"খাওয়া",on:"ショク",kun:"た(べる)"),
    KanjiItem(kanji:"飲",reading:"Nomu",meaning:"পান করা",on:"イン",kun:"の(む)"),
    KanjiItem(kanji:"買",reading:"Kau",meaning:"কেনা",on:"バイ",kun:"か(う)"),
    KanjiItem(kanji:"会",reading:"Au",meaning:"দেখা করা",on:"カイ",kun:"あ(う)"),
    KanjiItem(kanji:"店",reading:"Mise",meaning:"দোকান",on:"テン",kun:"みせ"),
  ],
  18: [
    KanjiItem(kanji:"駅",reading:"Eki",meaning:"স্টেশন",on:"エキ",kun:"—"),
    KanjiItem(kanji:"社",reading:"Sha",meaning:"প্রতিষ্ঠান / মন্দির",on:"シャ",kun:"やしろ"),
    KanjiItem(kanji:"道",reading:"Michi",meaning:"রাস্তা",on:"ドウ",kun:"みち"),
    KanjiItem(kanji:"国",reading:"Kuni",meaning:"দেশ",on:"コク",kun:"くに"),
    KanjiItem(kanji:"外",reading:"Soto",meaning:"বাইরে",on:"ガイ",kun:"そと"),
  ],
  19: [
    KanjiItem(kanji:"北",reading:"Kita",meaning:"উত্তর",on:"ホク",kun:"きた"),
    KanjiItem(kanji:"南",reading:"Minami",meaning:"দক্ষিণ",on:"ナン",kun:"みなみ"),
    KanjiItem(kanji:"東",reading:"Higashi",meaning:"পূর্ব",on:"トウ",kun:"ひがし"),
    KanjiItem(kanji:"西",reading:"Nishi",meaning:"পশ্চিম",on:"セイ, サイ",kun:"にし"),
    KanjiItem(kanji:"左",reading:"Hidari",meaning:"বাম",on:"サ",kun:"ひだり"),
  ],
  20: [
    KanjiItem(kanji:"右",reading:"Migi",meaning:"ডান",on:"ウ",kun:"みぎ"),
    KanjiItem(kanji:"中",reading:"Naka",meaning:"ভিতরে",on:"チュウ",kun:"なか"),
    KanjiItem(kanji:"上",reading:"Ue",meaning:"উপরে",on:"ジョウ",kun:"うえ"),
    KanjiItem(kanji:"下",reading:"Shita",meaning:"নিচে",on:"カ, ゲ",kun:"した"),
  ],
};

final Map<int, List<VocabItem>> vocabData = {
  0: [
    VocabItem(word:"1日",reading:"tsuitachi",meaning:"১ তারিখ"),
    VocabItem(word:"2日",reading:"futsuka",meaning:"২ তারিখ"),
    VocabItem(word:"3日",reading:"mikka",meaning:"৩ তারিখ"),
    VocabItem(word:"4日",reading:"yokka",meaning:"৪ তারিখ"),
    VocabItem(word:"5日",reading:"itsuka",meaning:"৫ তারিখ"),
    VocabItem(word:"6日",reading:"muika",meaning:"৬ তারিখ"),
    VocabItem(word:"7日",reading:"nanoka",meaning:"৭ তারিখ"),
    VocabItem(word:"8日",reading:"yooka",meaning:"৮ তারিখ"),
    VocabItem(word:"9日",reading:"kokonoka",meaning:"৯ তারিখ"),
    VocabItem(word:"10日",reading:"tooka",meaning:"১০ তারিখ"),
    VocabItem(word:"14日",reading:"juuyokka",meaning:"১৪ তারিখ"),
    VocabItem(word:"20日",reading:"hatsuika",meaning:"২০ তারিখ"),
    VocabItem(word:"24日",reading:"nijuuyokka",meaning:"২৪ তারিখ"),
    VocabItem(word:"1月",reading:"ichigatsu",meaning:"জানুয়ারি"),
    VocabItem(word:"2月",reading:"nigatsu",meaning:"ফেব্রুয়ারি"),
    VocabItem(word:"3月",reading:"sangatsu",meaning:"মার্চ"),
    VocabItem(word:"4月",reading:"shigatsu",meaning:"এপ্রিল"),
    VocabItem(word:"5月",reading:"gogatsu",meaning:"মে"),
    VocabItem(word:"6月",reading:"rokugatsu",meaning:"জুন"),
    VocabItem(word:"7月",reading:"shichigatsu",meaning:"জুলাই"),
    VocabItem(word:"8月",reading:"hachigatsu",meaning:"আগস্ট"),
    VocabItem(word:"9月",reading:"kugatsu",meaning:"সেপ্টেম্বর"),
    VocabItem(word:"10月",reading:"juugatsu",meaning:"অক্টোবর"),
    VocabItem(word:"11月",reading:"juuichigatsu",meaning:"নভেম্বর"),
    VocabItem(word:"12月",reading:"juunigatsu",meaning:"ডিসেম্বর"),
    VocabItem(word:"何月",reading:"nan-gatsu",meaning:"কোন মাস?"),
    VocabItem(word:"1日",reading:"tsuitachi",meaning:"১ তারিখ"),
    VocabItem(word:"2日",reading:"futsuka",meaning:"২ তারিখ"),
    VocabItem(word:"3日",reading:"mikka",meaning:"৩ তারিখ"),
    VocabItem(word:"4日",reading:"yokka",meaning:"৪ তারিখ"),
    VocabItem(word:"5日",reading:"itsuka",meaning:"৫ তারিখ"),
    VocabItem(word:"6日",reading:"muika",meaning:"৬ তারিখ"),
    VocabItem(word:"7日",reading:"nanoka",meaning:"৭ তারিখ"),
    VocabItem(word:"8日",reading:"yooka",meaning:"৮ তারিখ"),
    VocabItem(word:"9日",reading:"kokonoka",meaning:"৯ তারিখ"),
    VocabItem(word:"10日",reading:"tooka",meaning:"১০ তারিখ"),
    VocabItem(word:"14日",reading:"juuyokka",meaning:"১৪ তারিখ"),
    VocabItem(word:"20日",reading:"hatsuika",meaning:"২০ তারিখ"),
    VocabItem(word:"24日",reading:"nijuuyokka",meaning:"২৪ তারিখ"),
    VocabItem(word:"1月",reading:"ichigatsu",meaning:"জানুয়ারি"),
    VocabItem(word:"2月",reading:"nigatsu",meaning:"ফেব্রুয়ারি"),
    VocabItem(word:"3月",reading:"sangatsu",meaning:"মার্চ"),
    VocabItem(word:"4月",reading:"shigatsu",meaning:"এপ্রিল"),
    VocabItem(word:"5月",reading:"gogatsu",meaning:"মে"),
    VocabItem(word:"6月",reading:"rokugatsu",meaning:"জুন"),
    VocabItem(word:"7月",reading:"shichigatsu",meaning:"জুলাই"),
    VocabItem(word:"8月",reading:"hachigatsu",meaning:"আগস্ট"),
    VocabItem(word:"9月",reading:"kugatsu",meaning:"সেপ্টেম্বর"),
    VocabItem(word:"10月",reading:"juugatsu",meaning:"অক্টোবর"),
    VocabItem(word:"11月",reading:"juuichigatsu",meaning:"নভেম্বর"),
    VocabItem(word:"12月",reading:"juunigatsu",meaning:"ডিসেম্বর"),
    VocabItem(word:"何月",reading:"nan-gatsu",meaning:"কোন মাস?"),
  ],
  1: [
    VocabItem(word:"わたし",reading:"watashi",meaning:"আমি"),
    VocabItem(word:"私",reading:"watashi",meaning:"আমি"),
    VocabItem(word:"わたしたち",reading:"watashitachi",meaning:"আমরা"),
    VocabItem(word:"私たち",reading:"watashitachi",meaning:"আমরা"),
    VocabItem(word:"わたしの",reading:"watashi no",meaning:"আমার"),
    VocabItem(word:"私の",reading:"watashi no",meaning:"আমার"),
    VocabItem(word:"あなた",reading:"anata",meaning:"তুমি/আপনি"),
    VocabItem(word:"あなたの",reading:"anata no",meaning:"তোমার/আপনার"),
    VocabItem(word:"あのひと",reading:"ano hito",meaning:"ঐ ব্যক্তি, সে, তিনি"),
    VocabItem(word:"あの方",reading:"ano kata",meaning:"ঐ ব্যক্তি, সে, তিনি (সম্মানসূচক)"),
    VocabItem(word:"~さん",reading:"~san",meaning:"জনাব/জনাবা"),
    VocabItem(word:"~ちゃん",reading:"~chan",meaning:"সুনির্দিষ্ট শিশুর নামের পরে"),
    VocabItem(word:"~くん",reading:"~kun",meaning:"ছেলে বাচ্চার নামের পরে"),
    VocabItem(word:"~君",reading:"~kun",meaning:"ছেলে বাচ্চার নামের পরে"),
    VocabItem(word:"~じん",reading:"~jin",meaning:"নাগরিক"),
    VocabItem(word:"せんせい",reading:"sensei",meaning:"শিক্ষক"),
    VocabItem(word:"教師",reading:"kyooshi",meaning:"শিক্ষক"),
    VocabItem(word:"がくせい",reading:"gakusei",meaning:"ছাত্র/ছাত্রী"),
    VocabItem(word:"学生",reading:"gakusei",meaning:"ছাত্র/ছাত্রী"),
    VocabItem(word:"かいしゃいん",reading:"kaisha-in",meaning:"কোম্পানি কর্মচারী"),
    VocabItem(word:"会社員",reading:"kaisha-in",meaning:"কোম্পানি কর্মচারী"),
    VocabItem(word:"しゃいん",reading:"shain",meaning:"কর্মচারী"),
    VocabItem(word:"社員",reading:"shain",meaning:"কর্মচারী"),
    VocabItem(word:"ぎんこういん",reading:"ginkooin",meaning:"ব্যাংক কর্মচারী"),
    VocabItem(word:"銀行員",reading:"ginkooin",meaning:"ব্যাংক কর্মচারী"),
    VocabItem(word:"いしゃ",reading:"isha",meaning:"ডাক্তার"),
    VocabItem(word:"医者",reading:"isha",meaning:"ডাক্তার"),
    VocabItem(word:"けんきゅうしゃ",reading:"kenkyuusha",meaning:"গবেষক"),
    VocabItem(word:"研究者",reading:"kenkyuusha",meaning:"গবেষক"),
    VocabItem(word:"だいがく",reading:"daigaku",meaning:"বিশ্ববিদ্যালয়"),
    VocabItem(word:"大学",reading:"daigaku",meaning:"বিশ্ববিদ্যালয়"),
    VocabItem(word:"びょういん",reading:"byooin",meaning:"হাসপাতাল"),
    VocabItem(word:"病院",reading:"byooin",meaning:"হাসপাতাল"),
    VocabItem(word:"だれ",reading:"dare",meaning:"কে"),
    VocabItem(word:"どなた",reading:"donata",meaning:"কে (সম্মানসূচক)"),
    VocabItem(word:"~さい",reading:"~sai",meaning:"বয়স"),
    VocabItem(word:"なんさい",reading:"nansai",meaning:"কত বছর বয়স?"),
    VocabItem(word:"はい",reading:"hai",meaning:"হ্যাঁ"),
    VocabItem(word:"いいえ",reading:"iie",meaning:"না"),
    VocabItem(word:"れんしゅう",reading:"renshuu",meaning:"অনুশীলনী"),
    VocabItem(word:"しつれいですが",reading:"shitsurei desu ga",meaning:"দুঃখিত/মাফ করবেন, কিন্তু"),
    VocabItem(word:"おなまえは?",reading:"onamae wa?",meaning:"আপনার নাম জানতে পারি কি?"),
  ],
  2: [
    VocabItem(word:"これ",reading:"kore",meaning:"এটা"),
    VocabItem(word:"それ",reading:"sore",meaning:"ওটা"),
    VocabItem(word:"あれ",reading:"are",meaning:"ঐটা"),
    VocabItem(word:"この~",reading:"kono~",meaning:"এই"),
    VocabItem(word:"その~",reading:"sono~",meaning:"ওই"),
    VocabItem(word:"あの~",reading:"ano~",meaning:"ঐ"),
    VocabItem(word:"ほん",reading:"hon",meaning:"বই"),
    VocabItem(word:"本",reading:"hon",meaning:"বই"),
    VocabItem(word:"じしょ",reading:"jisho",meaning:"অভিধান"),
    VocabItem(word:"辞書",reading:"jisho",meaning:"অভিধান"),
    VocabItem(word:"ざっし",reading:"zasshi",meaning:"ম্যাগাজিন"),
    VocabItem(word:"雑誌",reading:"zasshi",meaning:"ম্যাগাজিন"),
    VocabItem(word:"しんぶん",reading:"shinbun",meaning:"পত্রিকা"),
    VocabItem(word:"新聞",reading:"shinbun",meaning:"পত্রিকা"),
    VocabItem(word:"ノート",reading:"nooto",meaning:"নোটবুক"),
    VocabItem(word:"てちょう",reading:"techou",meaning:"পকেট নোটবুক"),
    VocabItem(word:"手帳",reading:"techou",meaning:"পকেট নোটবুক"),
    VocabItem(word:"めいし",reading:"meishi",meaning:"বিজনেস কার্ড"),
    VocabItem(word:"名詞",reading:"meishi",meaning:"বিজনেস কার্ড"),
    VocabItem(word:"カード",reading:"kaado",meaning:"কার্ড"),
    VocabItem(word:"えんぴつ",reading:"enpitsu",meaning:"পেন্সিল"),
    VocabItem(word:"鉛筆",reading:"enpitsu",meaning:"পেন্সিল"),
    VocabItem(word:"ボールペン",reading:"booru-pen",meaning:"বল পয়েন্ট কলম"),
    VocabItem(word:"シャープペンシル",reading:"shaapu-penshiru",meaning:"যান্ত্রিক পেন্সিল"),
    VocabItem(word:"かぎ",reading:"kagi",meaning:"চাবি"),
    VocabItem(word:"とけい",reading:"tokei",meaning:"ঘড়ি"),
    VocabItem(word:"時計",reading:"tokei",meaning:"ঘড়ি"),
    VocabItem(word:"かさ",reading:"kasa",meaning:"ছাতা"),
    VocabItem(word:"傘",reading:"kasa",meaning:"ছাতা"),
    VocabItem(word:"かばん",reading:"kaban",meaning:"ব্যাগ"),
    VocabItem(word:"CD",reading:"CD",meaning:"CD"),
    VocabItem(word:"テレビ",reading:"terebi",meaning:"টেলিভিশন"),
    VocabItem(word:"ラジオ",reading:"rajio",meaning:"রেডিও"),
    VocabItem(word:"カメラ",reading:"kamera",meaning:"ক্যামেরা"),
    VocabItem(word:"コンピューター",reading:"konpyuuta",meaning:"কম্পিউটার"),
    VocabItem(word:"くるま",reading:"kuruma",meaning:"গাড়ি"),
    VocabItem(word:"つくえ",reading:"tsukue",meaning:"টেবিল"),
    VocabItem(word:"いす",reading:"isu",meaning:"চেয়ার"),
    VocabItem(word:"チョコレート",reading:"chokoreeto",meaning:"চকোলেট"),
    VocabItem(word:"コーヒー",reading:"koohii",meaning:"কফি"),
    VocabItem(word:"おみやげ",reading:"omiyage",meaning:"সামান্য উপহার"),
    VocabItem(word:"えいご",reading:"eigo",meaning:"ইংরেজি ভাষা"),
    VocabItem(word:"英語",reading:"eigo",meaning:"ইংরেজি ভাষা"),
    VocabItem(word:"にほんご",reading:"nihongo",meaning:"জাপানি ভাষা"),
    VocabItem(word:"日本語",reading:"nihongo",meaning:"জাপানি ভাষা"),
    VocabItem(word:"~ご",reading:"~go",meaning:"~ ভাষা"),
    VocabItem(word:"なん",reading:"nan",meaning:"কি"),
    VocabItem(word:"何",reading:"nan",meaning:"কি"),
    VocabItem(word:"そう",reading:"soo",meaning:"তাই"),
    VocabItem(word:"れんしゅう",reading:"renshuu",meaning:"অনুশীলনী"),
    VocabItem(word:"練習",reading:"renshuu",meaning:"অনুশীলনী"),
    VocabItem(word:"あのう",reading:"anou",meaning:"ভালো (দ্বিধা প্রকাশে)"),
  ],
  3: [
    VocabItem(word:"ここ",reading:"koko",meaning:"এখানে"),
    VocabItem(word:"そこ",reading:"soko",meaning:"ওখানে"),
    VocabItem(word:"あそこ",reading:"asoko",meaning:"ঐখানে"),
    VocabItem(word:"どこ",reading:"doko",meaning:"কোথায়"),
    VocabItem(word:"こちら",reading:"kochira",meaning:"এই দিকে"),
    VocabItem(word:"そちら",reading:"sochira",meaning:"ওই দিকে"),
    VocabItem(word:"あちら",reading:"achira",meaning:"ঐ দিকে"),
    VocabItem(word:"どちら",reading:"dochira",meaning:"কোন দিকে"),
    VocabItem(word:"教室",reading:"kyooshitsu",meaning:"শ্রেণীকক্ষ"),
    VocabItem(word:"食堂",reading:"shokudou",meaning:"খাবার জায়গা"),
    VocabItem(word:"事務所",reading:"jimusho",meaning:"অফিস"),
    VocabItem(word:"会議室",reading:"kaigishitsu",meaning:"মিটিং রুম"),
    VocabItem(word:"受付",reading:"uketsuke",meaning:"অভ্যর্থনা"),
    VocabItem(word:"ロビー",reading:"robii",meaning:"লবি"),
    VocabItem(word:"部屋",reading:"heya",meaning:"কক্ষ"),
    VocabItem(word:"トイレ",reading:"toire",meaning:"টয়লেট"),
    VocabItem(word:"階段",reading:"kaidan",meaning:"সিঁড়ি"),
    VocabItem(word:"エレベーター",reading:"erebeetaa",meaning:"এলেভেটর"),
    VocabItem(word:"エスカレーター",reading:"esukareetaa",meaning:"চলন্ত সিঁড়ি"),
    VocabItem(word:"自動販売機",reading:"jidou hanbaiki",meaning:"অটো বিক্রয় মেশিন"),
    VocabItem(word:"電話",reading:"denwa",meaning:"টেলিফোন"),
    VocabItem(word:"お国",reading:"okuni",meaning:"দেশ"),
    VocabItem(word:"会社",reading:"kaisha",meaning:"কোম্পানি"),
    VocabItem(word:"家",reading:"uchi",meaning:"বাড়ি"),
    VocabItem(word:"靴",reading:"kutsu",meaning:"জুতা"),
    VocabItem(word:"ネクタイ",reading:"nekutai",meaning:"টাই"),
    VocabItem(word:"売り場",reading:"uriba",meaning:"কাউন্টার"),
    VocabItem(word:"地下",reading:"chika",meaning:"নিচতলা"),
    VocabItem(word:"~階",reading:"~kai",meaning:"~ তলা"),
    VocabItem(word:"何階",reading:"nangai",meaning:"কোন তলা"),
    VocabItem(word:"~円",reading:"~en",meaning:"ইয়েন"),
    VocabItem(word:"いくら",reading:"ikura",meaning:"দাম কত"),
    VocabItem(word:"百",reading:"hyaku",meaning:"একশত"),
    VocabItem(word:"千",reading:"sen",meaning:"হাজার"),
    VocabItem(word:"万",reading:"man",meaning:"দশ হাজার"),
    VocabItem(word:"練習",reading:"renshuu",meaning:"অনুশীলনী"),
    VocabItem(word:"すみません",reading:"sumimasen",meaning:"দুঃখিত"),
    VocabItem(word:"どうも",reading:"doumo",meaning:"ধন্যবাদ"),
    VocabItem(word:"会話",reading:"kaiwa",meaning:"কথা-বার্তা"),
    VocabItem(word:"いらっしゃいませ",reading:"irasshaimase",meaning:"স্বাগতম"),
    VocabItem(word:"みせてください",reading:"misete kudasai",meaning:"দেখান"),
    VocabItem(word:"じゃ",reading:"ja",meaning:"তাহলে"),
    VocabItem(word:"ください",reading:"kudasai",meaning:"দেন"),
  ],
  4: [
    VocabItem(word:"おきます",reading:"okimasu",meaning:"ঘুম থেকে উঠা"),
    VocabItem(word:"ねます",reading:"nemasu",meaning:"ঘুমানো"),
    VocabItem(word:"はたらきます",reading:"hatarakimasu",meaning:"কাজ করা"),
    VocabItem(word:"やすみます",reading:"yasumimasu",meaning:"বিশ্রাম নেওয়া"),
    VocabItem(word:"べんきょうします",reading:"benkyou shimasu",meaning:"পড়াশোনা করা"),
    VocabItem(word:"おわります",reading:"owarimasu",meaning:"শেষ করা"),
    VocabItem(word:"デパート",reading:"depaato",meaning:"ডিপার্টমেন্ট স্টোর"),
    VocabItem(word:"銀行",reading:"ginkou",meaning:"ব্যাংক"),
    VocabItem(word:"郵便局",reading:"yuubinkyoku",meaning:"ডাকঘর"),
    VocabItem(word:"図書館",reading:"toshokan",meaning:"গ্রন্থাগার"),
    VocabItem(word:"美術館",reading:"bijutsukan",meaning:"শিল্প জাদুঘর"),
    VocabItem(word:"いま",reading:"ima",meaning:"এখন"),
    VocabItem(word:"~時",reading:"~ji",meaning:"~টা"),
    VocabItem(word:"~分",reading:"~fun",meaning:"~মিনিট"),
    VocabItem(word:"半",reading:"han",meaning:"অর্ধেক"),
    VocabItem(word:"何時",reading:"nanji",meaning:"কটা বাজে"),
    VocabItem(word:"何分",reading:"nanbun",meaning:"কত মিনিট"),
    VocabItem(word:"午前",reading:"gozen",meaning:"সকাল"),
    VocabItem(word:"午後",reading:"gogo",meaning:"বিকেল"),
    VocabItem(word:"朝",reading:"asa",meaning:"সকাল"),
    VocabItem(word:"昼",reading:"hiru",meaning:"দুপুর"),
    VocabItem(word:"晩",reading:"ban",meaning:"রাত"),
    VocabItem(word:"おととい",reading:"ototoi",meaning:"গত পরশু"),
    VocabItem(word:"きのう",reading:"kinou",meaning:"গতকাল"),
    VocabItem(word:"きょう",reading:"kyou",meaning:"আজ"),
    VocabItem(word:"あした",reading:"ashita",meaning:"আগামীকাল"),
    VocabItem(word:"あさって",reading:"asatte",meaning:"আগামী পরশু"),
    VocabItem(word:"今朝",reading:"kesa",meaning:"আজ সকাল"),
    VocabItem(word:"今晩",reading:"konban",meaning:"আজ রাত"),
    VocabItem(word:"休み",reading:"yasumi",meaning:"ছুটি"),
    VocabItem(word:"昼休み",reading:"hiruyasumi",meaning:"দুপুরের বিরতি"),
    VocabItem(word:"試験",reading:"shiken",meaning:"পরীক্ষা"),
    VocabItem(word:"会議",reading:"kaigi",meaning:"মিটিং"),
    VocabItem(word:"映画",reading:"eiga",meaning:"সিনেমা"),
    VocabItem(word:"毎朝",reading:"maiasa",meaning:"প্রতি সকাল"),
    VocabItem(word:"毎晩",reading:"maiban",meaning:"প্রতি রাত"),
    VocabItem(word:"毎日",reading:"mainichi",meaning:"প্রতিদিন"),
    VocabItem(word:"月曜日",reading:"getsuyoubi",meaning:"সোমবার"),
    VocabItem(word:"火曜日",reading:"kayoubi",meaning:"মঙ্গলবার"),
    VocabItem(word:"水曜日",reading:"suiyoubi",meaning:"বুধবার"),
    VocabItem(word:"木曜日",reading:"mokuyoubi",meaning:"বৃহস্পতিবার"),
    VocabItem(word:"金曜日",reading:"kinyoubi",meaning:"শুক্রবার"),
    VocabItem(word:"土曜日",reading:"doyoubi",meaning:"শনিবার"),
    VocabItem(word:"日曜日",reading:"nichiyoubi",meaning:"রবিবার"),
    VocabItem(word:"何曜日",reading:"nanyoubi",meaning:"কোন বার"),
    VocabItem(word:"~から",reading:"~kara",meaning:"থেকে"),
    VocabItem(word:"~まで",reading:"~made",meaning:"পর্যন্ত"),
    VocabItem(word:"~と~",reading:"~to~",meaning:"এবং"),
  ],
  5: [
    VocabItem(word:"いきます",reading:"ikimasu",meaning:"যাওয়া"),
    VocabItem(word:"きます",reading:"kimasu",meaning:"আসা"),
    VocabItem(word:"かえります",reading:"kaerimasu",meaning:"ফিরে আসা"),
    VocabItem(word:"学校",reading:"gakkou",meaning:"বিদ্যালয়"),
    VocabItem(word:"スーパー",reading:"suupaa",meaning:"সুপার মার্কেট"),
    VocabItem(word:"駅",reading:"eki",meaning:"স্টেশন"),
    VocabItem(word:"船",reading:"fune",meaning:"জাহাজ"),
    VocabItem(word:"飛行機",reading:"hikouki",meaning:"বিমান"),
    VocabItem(word:"電車",reading:"densha",meaning:"ট্রেন"),
    VocabItem(word:"地下鉄",reading:"chikatetsu",meaning:"সাবওয়ে"),
    VocabItem(word:"新幹線",reading:"shinkansen",meaning:"বুলেট ট্রেন"),
    VocabItem(word:"バス",reading:"basu",meaning:"বাস"),
    VocabItem(word:"タクシー",reading:"takushii",meaning:"ট্যাক্সি"),
    VocabItem(word:"自転車",reading:"jitensha",meaning:"বাইসাইকেল"),
    VocabItem(word:"歩いて",reading:"aruite",meaning:"পায়ে হেঁটে"),
    VocabItem(word:"人",reading:"hito",meaning:"ব্যক্তি"),
    VocabItem(word:"友達",reading:"tomodachi",meaning:"বন্ধু"),
    VocabItem(word:"彼",reading:"kare",meaning:"সে"),
    VocabItem(word:"彼女",reading:"kanojo",meaning:"সে"),
    VocabItem(word:"家族",reading:"kazoku",meaning:"পরিবার"),
    VocabItem(word:"一人で",reading:"hitoride",meaning:"একাকী"),
    VocabItem(word:"先週",reading:"senshuu",meaning:"গত সপ্তাহ"),
    VocabItem(word:"今週",reading:"konshuu",meaning:"এই সপ্তাহ"),
    VocabItem(word:"来週",reading:"raishuu",meaning:"আগামী সপ্তাহ"),
    VocabItem(word:"先月",reading:"sengetsu",meaning:"গত মাস"),
    VocabItem(word:"今月",reading:"kongetsu",meaning:"এই মাস"),
    VocabItem(word:"来月",reading:"raigetsu",meaning:"আগামী মাস"),
    VocabItem(word:"去年",reading:"kyonen",meaning:"গত বছর"),
    VocabItem(word:"今年",reading:"kotoshi",meaning:"এই বছর"),
    VocabItem(word:"来年",reading:"rainen",meaning:"আগামী বছর"),
    VocabItem(word:"年",reading:"-nen",meaning:"বছর"),
    VocabItem(word:"何年",reading:"nannen",meaning:"কোন বছর"),
    VocabItem(word:"―月",reading:"-gatsu",meaning:"মাস"),
    VocabItem(word:"何月",reading:"nangatsu",meaning:"কোন মাস"),
    VocabItem(word:"１日",reading:"tsuitachi",meaning:"১ তারিখ"),
    VocabItem(word:"２日",reading:"futsuka",meaning:"২ তারিখ"),
    VocabItem(word:"３日",reading:"mikka",meaning:"৩ তারিখ"),
    VocabItem(word:"４日",reading:"yokka",meaning:"৪ তারিখ"),
    VocabItem(word:"５日",reading:"itsuka",meaning:"৫ তারিখ"),
    VocabItem(word:"６日",reading:"muika",meaning:"৬ তারিখ"),
    VocabItem(word:"７日",reading:"nanoka",meaning:"৭ তারিখ"),
    VocabItem(word:"８日",reading:"youka",meaning:"৮ তারিখ"),
    VocabItem(word:"９日",reading:"kokonoka",meaning:"৯ তারিখ"),
    VocabItem(word:"１０日",reading:"tooka",meaning:"১০ তারিখ"),
    VocabItem(word:"１４日",reading:"juuyokka",meaning:"১৪ তারিখ"),
    VocabItem(word:"２０日",reading:"hatsuka",meaning:"২০ তারিখ"),
    VocabItem(word:"２４日",reading:"nijuuyokka",meaning:"২৪ তারিখ"),
    VocabItem(word:"～日",reading:"~nichi",meaning:"~ তারিখ"),
    VocabItem(word:"何日",reading:"nannichi",meaning:"কোন তারিখ"),
    VocabItem(word:"いつ",reading:"itsu",meaning:"কখন"),
    VocabItem(word:"誕生日",reading:"tanjoubi",meaning:"জন্মদিন"),
  ],
  6: [
    VocabItem(word:"食べます",reading:"tabemasu",meaning:"খাওয়া"),
    VocabItem(word:"飲みます",reading:"nomimasu",meaning:"পান করা"),
    VocabItem(word:"吸います",reading:"suimasu",meaning:"ধূমপান করা"),
    VocabItem(word:"見ます",reading:"mimasu",meaning:"দেখা"),
    VocabItem(word:"聞きます",reading:"kikimasu",meaning:"শোনা"),
    VocabItem(word:"読みます",reading:"yomimasu",meaning:"পড়া"),
    VocabItem(word:"書きます",reading:"kakimasu",meaning:"লেখা"),
    VocabItem(word:"買います",reading:"kaimasu",meaning:"ক্রয় করা"),
    VocabItem(word:"取ります",reading:"torimasu",meaning:"তোলা"),
    VocabItem(word:"します",reading:"shimasu",meaning:"করা"),
    VocabItem(word:"会います",reading:"aimasu",meaning:"সাক্ষাৎ করা"),
    VocabItem(word:"ご飯",reading:"gohan",meaning:"খাবার"),
    VocabItem(word:"朝ごはん",reading:"asagohan",meaning:"সকালের খাবার"),
    VocabItem(word:"昼ごはん",reading:"hirugohan",meaning:"দুপুরের খাবার"),
    VocabItem(word:"晩ごはん",reading:"bangohan",meaning:"রাতের খাবার"),
    VocabItem(word:"パン",reading:"pan",meaning:"রুটি"),
    VocabItem(word:"卵",reading:"tamago",meaning:"ডিম"),
    VocabItem(word:"肉",reading:"niku",meaning:"মাংস"),
    VocabItem(word:"魚",reading:"sakana",meaning:"মাছ"),
    VocabItem(word:"野菜",reading:"yasai",meaning:"শাকসবজি"),
    VocabItem(word:"果物",reading:"kudamono",meaning:"ফল"),
    VocabItem(word:"水",reading:"mizu",meaning:"পানি"),
    VocabItem(word:"お茶",reading:"ocha",meaning:"চা"),
    VocabItem(word:"紅茶",reading:"koucha",meaning:"কালো চা"),
    VocabItem(word:"牛乳",reading:"gyuunyuu",meaning:"দুধ"),
    VocabItem(word:"ジュース",reading:"juusu",meaning:"জুস"),
    VocabItem(word:"ビール",reading:"biiru",meaning:"বিয়ার"),
    VocabItem(word:"お酒",reading:"osake",meaning:"সাকে"),
    VocabItem(word:"煙草",reading:"tabako",meaning:"সিগারেট"),
    VocabItem(word:"手紙",reading:"tegami",meaning:"চিঠি"),
    VocabItem(word:"レポート",reading:"repooto",meaning:"রিপোর্ট"),
    VocabItem(word:"写真",reading:"shashin",meaning:"ছবি"),
    VocabItem(word:"ビデオ",reading:"bideo",meaning:"ভিডিও"),
    VocabItem(word:"店",reading:"mise",meaning:"দোকান"),
    VocabItem(word:"庭",reading:"niwa",meaning:"বাগান"),
    VocabItem(word:"宿題",reading:"shukudai",meaning:"বাড়ির কাজ"),
    VocabItem(word:"テニス",reading:"tenisu",meaning:"টেনিস"),
    VocabItem(word:"サッカー",reading:"sakkaa",meaning:"ফুটবল"),
    VocabItem(word:"お花見",reading:"ohanami",meaning:"চেরি ফুলের উৎসব"),
    VocabItem(word:"何",reading:"nani",meaning:"কি"),
    VocabItem(word:"一緒に",reading:"isshoni",meaning:"একসাথে"),
    VocabItem(word:"ちょっと",reading:"chotto",meaning:"অল্প"),
    VocabItem(word:"いつも",reading:"itsumo",meaning:"সবসময়"),
    VocabItem(word:"時々",reading:"tokidoki",meaning:"মাঝেমাঝে"),
    VocabItem(word:"それから",reading:"sorekara",meaning:"এরপরে"),
    VocabItem(word:"ええ",reading:"ee",meaning:"হ্যাঁ"),
    VocabItem(word:"いいですね",reading:"iidesune",meaning:"ভালো"),
    VocabItem(word:"分かりました",reading:"wakari mashita",meaning:"বুঝেছি"),
  ],
  7: [
    VocabItem(word:"切ります",reading:"kirimasu",meaning:"কাটা"),
    VocabItem(word:"送ります",reading:"okurimasu",meaning:"পাঠানো"),
    VocabItem(word:"上げます",reading:"agemasu",meaning:"দেওয়া"),
    VocabItem(word:"貰います",reading:"moraimasu",meaning:"গ্রহণ করা"),
    VocabItem(word:"貸します",reading:"kashimasu",meaning:"ধার দেওয়া"),
    VocabItem(word:"借ります",reading:"karimasu",meaning:"ধার করা"),
    VocabItem(word:"教えます",reading:"oshiemasu",meaning:"শিখানো"),
    VocabItem(word:"習います",reading:"naraimasu",meaning:"শেখা"),
    VocabItem(word:"かけます",reading:"kakemasu",meaning:"কল করা"),
    VocabItem(word:"手",reading:"te",meaning:"হাত"),
    VocabItem(word:"はし",reading:"hashi",meaning:"কাঠি"),
    VocabItem(word:"スプーン",reading:"supuun",meaning:"চামচ"),
    VocabItem(word:"ナイフ",reading:"naifu",meaning:"ছুরি"),
    VocabItem(word:"フォーク",reading:"fooku",meaning:"কাঁটা চামচ"),
    VocabItem(word:"はさみ",reading:"hasami",meaning:"কাঁচি"),
    VocabItem(word:"パソコン",reading:"pasokon",meaning:"কম্পিউটার"),
    VocabItem(word:"ケータイ",reading:"keetai",meaning:"মোবাইল"),
    VocabItem(word:"メール",reading:"meeru",meaning:"মেইল"),
    VocabItem(word:"年賀状",reading:"nengajou",meaning:"নববর্ষের কার্ড"),
    VocabItem(word:"パンチ",reading:"panchi",meaning:"পাঞ্চ"),
    VocabItem(word:"ホッチキス",reading:"hotchikisu",meaning:"স্টেপলার"),
    VocabItem(word:"セロテープ",reading:"seroteepu",meaning:"স্কচটেপ"),
    VocabItem(word:"消しゴム",reading:"keshigomu",meaning:"ইরেজার"),
    VocabItem(word:"紙",reading:"kami",meaning:"কাগজ"),
    VocabItem(word:"花",reading:"hana",meaning:"ফুল"),
    VocabItem(word:"シャツ",reading:"shatsu",meaning:"শার্ট"),
    VocabItem(word:"プレゼント",reading:"purezento",meaning:"উপহার"),
    VocabItem(word:"荷物",reading:"nimotsu",meaning:"মালপত্র"),
    VocabItem(word:"お金",reading:"okane",meaning:"টাকা"),
    VocabItem(word:"切符",reading:"kippu",meaning:"টিকেট"),
    VocabItem(word:"クリスマス",reading:"kurisumasu",meaning:"ক্রিসমাস"),
    VocabItem(word:"父",reading:"chichi",meaning:"বাবা"),
    VocabItem(word:"母",reading:"haha",meaning:"মা"),
    VocabItem(word:"お父さん",reading:"otousan",meaning:"অন্যের বাবা"),
    VocabItem(word:"お母さん",reading:"okaasan",meaning:"অন্যের মা"),
    VocabItem(word:"もう",reading:"mou",meaning:"ইতিমধ্যে"),
    VocabItem(word:"まだ",reading:"mada",meaning:"এখনো না"),
    VocabItem(word:"これから",reading:"korekara",meaning:"এখন থেকে"),
  ],
  8: [
    VocabItem(word:"ハンサム[な]",reading:"hansamu[na]",meaning:"সুদর্শন"),
    VocabItem(word:"きれい[な]",reading:"kirei[na]",meaning:"সুন্দর"),
    VocabItem(word:"しずか[な]",reading:"shizuka[na]",meaning:"শান্ত"),
    VocabItem(word:"にぎやか[な]",reading:"nigiyaka[na]",meaning:"জমজমাট"),
    VocabItem(word:"ゆうめい[な]",reading:"yuumei[na]",meaning:"বিখ্যাত"),
    VocabItem(word:"しんせつ[な]",reading:"shinsetsu[na]",meaning:"দয়ালু"),
    VocabItem(word:"げんき[な]",reading:"genki[na]",meaning:"স্বাস্থ্যবান"),
    VocabItem(word:"ひま[な]",reading:"hima[na]",meaning:"অবসর"),
    VocabItem(word:"べんり[な]",reading:"benri[na]",meaning:"সুবিধাজনক"),
    VocabItem(word:"すてき[な]",reading:"suteki[na]",meaning:"চমৎকার"),
    VocabItem(word:"大きい",reading:"ookii",meaning:"বড়"),
    VocabItem(word:"小さい",reading:"chiisai",meaning:"ছোট"),
    VocabItem(word:"新しい",reading:"atarashii",meaning:"নতুন"),
    VocabItem(word:"古い",reading:"furui",meaning:"পুরাতন"),
    VocabItem(word:"いい(よい)",reading:"ii(yoi)",meaning:"ভালো"),
    VocabItem(word:"悪い",reading:"warui",meaning:"খারাপ"),
    VocabItem(word:"暑い",reading:"atsui",meaning:"গরম"),
    VocabItem(word:"寒い",reading:"samui",meaning:"ঠান্ডা"),
    VocabItem(word:"冷たい",reading:"tsumetai",meaning:"ঠান্ডা"),
    VocabItem(word:"難しい",reading:"muzukashii",meaning:"কঠিন"),
    VocabItem(word:"易しい",reading:"yasashii",meaning:"সহজ"),
    VocabItem(word:"高い",reading:"takai",meaning:"দামি/উঁচু"),
    VocabItem(word:"安い",reading:"yasui",meaning:"সস্তা"),
    VocabItem(word:"低い",reading:"hikui",meaning:"নিচু"),
    VocabItem(word:"面白い",reading:"omoshiroi",meaning:"মজার"),
    VocabItem(word:"おいしい",reading:"oishii",meaning:"সুস্বাদু"),
    VocabItem(word:"忙しい",reading:"isogashii",meaning:"ব্যস্ত"),
    VocabItem(word:"楽しい",reading:"tanoshii",meaning:"আনন্দদায়ক"),
    VocabItem(word:"白い",reading:"shiroi",meaning:"সাদা"),
    VocabItem(word:"黒い",reading:"kuroi",meaning:"কালো"),
    VocabItem(word:"赤い",reading:"akai",meaning:"লাল"),
    VocabItem(word:"青い",reading:"aoi",meaning:"নীল"),
  ],
  9: [
    VocabItem(word:"分かります",reading:"wakarimasu",meaning:"বুঝতে পারা"),
    VocabItem(word:"あります",reading:"arimasu",meaning:"আছে"),
    VocabItem(word:"好き[な]",reading:"suki[na]",meaning:"পছন্দ"),
    VocabItem(word:"嫌い[な]",reading:"kirai[na]",meaning:"অপছন্দ"),
    VocabItem(word:"上手[な]",reading:"jouzu[na]",meaning:"দক্ষ"),
    VocabItem(word:"下手[な]",reading:"heta[na]",meaning:"অদক্ষ"),
    VocabItem(word:"飲み物",reading:"nomimono",meaning:"পানীয়"),
    VocabItem(word:"料理",reading:"ryouri",meaning:"রান্না"),
    VocabItem(word:"スポーツ",reading:"supootsu",meaning:"খেলাধুলা"),
    VocabItem(word:"野球",reading:"yakyuu",meaning:"বেসবল"),
    VocabItem(word:"ダンス",reading:"dansu",meaning:"নাচ"),
    VocabItem(word:"旅行",reading:"ryokou",meaning:"ভ্রমণ"),
    VocabItem(word:"音楽",reading:"ongaku",meaning:"সংগীত"),
    VocabItem(word:"歌",reading:"uta",meaning:"গান"),
    VocabItem(word:"クラシック",reading:"kurashikku",meaning:"ক্লাসিক্যাল"),
    VocabItem(word:"ジャズ",reading:"jazu",meaning:"জাজ"),
    VocabItem(word:"コンサート",reading:"konsaato",meaning:"কনসার্ট"),
    VocabItem(word:"カラオケ",reading:"karaoke",meaning:"কারাওকে"),
    VocabItem(word:"歌舞伎",reading:"kabuki",meaning:"কাবুকি"),
    VocabItem(word:"絵",reading:"e",meaning:"ছবি"),
    VocabItem(word:"字",reading:"ji",meaning:"অক্ষর"),
    VocabItem(word:"漢字",reading:"kanji",meaning:"কাঞ্জি"),
    VocabItem(word:"ひらがな",reading:"hiragana",meaning:"হিরাগানা"),
    VocabItem(word:"カタカナ",reading:"katakana",meaning:"কাতাকানা"),
    VocabItem(word:"ローマジ",reading:"roomaji",meaning:"রোমাজি"),
    VocabItem(word:"細かいお金",reading:"komakai okane",meaning:"খুচরা টাকা"),
    VocabItem(word:"チケット",reading:"chiketto",meaning:"টিকেট"),
    VocabItem(word:"時間",reading:"jikan",meaning:"সময়"),
    VocabItem(word:"用事",reading:"youji",meaning:"কাজ"),
    VocabItem(word:"約束",reading:"yakusoku",meaning:"প্রতিশ্রুতি"),
    VocabItem(word:"あるばいと",reading:"arubaito",meaning:"পার্টটাইম চাকরি"),
    VocabItem(word:"ご主人",reading:"goshujin",meaning:"অন্যের স্বামী"),
    VocabItem(word:"夫/主人",reading:"otto/shujin",meaning:"আমার স্বামী"),
    VocabItem(word:"奥さん",reading:"okusan",meaning:"অন্যের স্ত্রী"),
    VocabItem(word:"妻/家内",reading:"tsuma/kanai",meaning:"আমার স্ত্রী"),
    VocabItem(word:"子供",reading:"kodomo",meaning:"শিশু"),
    VocabItem(word:"よく",reading:"yoku",meaning:"প্রায়ই"),
    VocabItem(word:"だいたい",reading:"daitai",meaning:"অধিকাংশ"),
    VocabItem(word:"たくさん",reading:"takusan",meaning:"অনেক"),
    VocabItem(word:"少し",reading:"sukoshi",meaning:"কম"),
    VocabItem(word:"全然",reading:"zenzen",meaning:"একদমই না"),
    VocabItem(word:"早く",reading:"hayaku",meaning:"দ্রুত"),
    VocabItem(word:"~kara",reading:"~kara",meaning:"কারণ"),
    VocabItem(word:"どうして/なぜ",reading:"doushite/naze",meaning:"কেন"),
  ],
  10: [
    VocabItem(word:"います",reading:"imasu",meaning:"আছে"),
    VocabItem(word:"あります",reading:"arimasu",meaning:"আছে"),
    VocabItem(word:"いろいろ[な]",reading:"iroiro[na]",meaning:"বিভিন্ন"),
    VocabItem(word:"男の人",reading:"otokonohito",meaning:"পুরুষ"),
    VocabItem(word:"女の人",reading:"onnanohito",meaning:"মহিলা"),
    VocabItem(word:"男の子",reading:"otokonoko",meaning:"ছেলে"),
    VocabItem(word:"女の子",reading:"onnanoko",meaning:"মেয়ে"),
    VocabItem(word:"犬",reading:"inu",meaning:"কুকুর"),
    VocabItem(word:"猫",reading:"neko",meaning:"বিড়াল"),
    VocabItem(word:"パンダ",reading:"panda",meaning:"পান্ডা"),
    VocabItem(word:"象",reading:"zou",meaning:"হাতি"),
    VocabItem(word:"木",reading:"ki",meaning:"গাছ"),
    VocabItem(word:"物",reading:"mono",meaning:"জিনিস"),
    VocabItem(word:"電池",reading:"denchi",meaning:"ব্যাটারি"),
    VocabItem(word:"箱",reading:"hako",meaning:"বাক্স"),
    VocabItem(word:"スイッチ",reading:"suicchi",meaning:"সুইচ"),
    VocabItem(word:"冷蔵庫",reading:"reizouko",meaning:"ফ্রিজ"),
    VocabItem(word:"テーブル",reading:"teeburu",meaning:"টেবিল"),
    VocabItem(word:"ベッド",reading:"beddo",meaning:"বিছানা"),
    VocabItem(word:"棚",reading:"tana",meaning:"তাক"),
    VocabItem(word:"ドア",reading:"doa",meaning:"দরজা"),
    VocabItem(word:"窓",reading:"mado",meaning:"জানালা"),
    VocabItem(word:"ポスト",reading:"posuto",meaning:"ডাকবাক্স"),
    VocabItem(word:"ビル",reading:"biru",meaning:"বিল্ডিং"),
    VocabItem(word:"ATM",reading:"ATM",meaning:"এটিএম"),
    VocabItem(word:"コンビニ",reading:"konbini",meaning:"সুবিধাজনক দোকান"),
    VocabItem(word:"公園",reading:"kouen",meaning:"পার্ক"),
    VocabItem(word:"喫茶店",reading:"kissaten",meaning:"কফি দোকান"),
    VocabItem(word:"本屋",reading:"honya",meaning:"বইয়ের দোকান"),
    VocabItem(word:"~屋",reading:"~ya",meaning:"~দোকান"),
    VocabItem(word:"乗り場",reading:"noriba",meaning:"নির্দিষ্ট জায়গা"),
    VocabItem(word:"県",reading:"ken",meaning:"অঞ্চল"),
    VocabItem(word:"上",reading:"ue",meaning:"উপরে"),
    VocabItem(word:"下",reading:"shita",meaning:"নিচে"),
    VocabItem(word:"前",reading:"mae",meaning:"সামনে"),
    VocabItem(word:"後ろ",reading:"ushiro",meaning:"পিছনে"),
    VocabItem(word:"右",reading:"migi",meaning:"ডানে"),
    VocabItem(word:"左",reading:"hidari",meaning:"বামে"),
    VocabItem(word:"中",reading:"naka",meaning:"মধ্যে"),
    VocabItem(word:"外",reading:"soto",meaning:"বাইরে"),
    VocabItem(word:"隣",reading:"tonari",meaning:"পাশে"),
    VocabItem(word:"近く",reading:"chikaku",meaning:"কাছে"),
    VocabItem(word:"間",reading:"aida",meaning:"মাঝখানে"),
    VocabItem(word:"~や~【など】",reading:"~ya~[nado]",meaning:"ইত্যাদি"),
    VocabItem(word:"会話",reading:"kaiwa",meaning:"কথা-বার্তা"),
    VocabItem(word:"[どうも] すみません",reading:"[doumo] sumimasen",meaning:"ধন্যবাদ / দুঃখিত"),
    VocabItem(word:"ナンプラー",reading:"nanpuraa",meaning:"নাম প্লা"),
    VocabItem(word:"コーナー",reading:"koonaa",meaning:"কর্নার"),
    VocabItem(word:"一番~",reading:"ichiban~",meaning:"সবচেয়ে"),
    VocabItem(word:"とうきょうディズニーランド",reading:"toukyou dizuniirando",meaning:"টোকিও ডিজনিল্যান্ড"),
    VocabItem(word:"アジアストア",reading:"ajiasutoa",meaning:"আশিয়া স্টোর"),
  ],
  11: [
    VocabItem(word:"います[子供が~]",reading:"imasu[kodomoga~]",meaning:"আছে [বাচ্চা]"),
    VocabItem(word:"かかります",reading:"kakakrimasu",meaning:"প্রয়োজন, নেওয়া"),
    VocabItem(word:"やすみます[会社を~]",reading:"yasumimasu[kaishao~]",meaning:"ছুটি নেওয়া"),
    VocabItem(word:"ひとつ",reading:"hitotsu",meaning:"একটি"),
    VocabItem(word:"ふたつ",reading:"futatsu",meaning:"দুইটি"),
    VocabItem(word:"みっつ",reading:"mittsu",meaning:"তিনটি"),
    VocabItem(word:"よっつ",reading:"yottsu",meaning:"চারটি"),
    VocabItem(word:"いつつ",reading:"itsutsu",meaning:"পাঁচটি"),
    VocabItem(word:"むっつ",reading:"muttsu",meaning:"ছয়টি"),
    VocabItem(word:"ななつ",reading:"nanatsu",meaning:"সাতটি"),
    VocabItem(word:"やっつ",reading:"yattsu",meaning:"আটটি"),
    VocabItem(word:"ここのつ",reading:"kokonotsu",meaning:"নয়টি"),
    VocabItem(word:"とお",reading:"too",meaning:"দশটি"),
    VocabItem(word:"いくつ",reading:"ikutsu",meaning:"কয়টি?"),
    VocabItem(word:"ひとり",reading:"hitori",meaning:"একজন"),
    VocabItem(word:"ふたり",reading:"futari",meaning:"দুইজন"),
    VocabItem(word:"~にん",reading:"~nin",meaning:"~জন"),
    VocabItem(word:"~だい",reading:"~dai",meaning:"~টি (যন্ত্রপাতি)"),
    VocabItem(word:"~まい",reading:"~mai",meaning:"~টি (পাতলা জিনিস)"),
    VocabItem(word:"~かい",reading:"~kai",meaning:"~বার"),
    VocabItem(word:"りんご",reading:"ringo",meaning:"আপেল"),
    VocabItem(word:"みかん",reading:"mikan",meaning:"কমলা"),
    VocabItem(word:"サンドイッチ",reading:"sandoicchi",meaning:"স্যান্ডুইচ"),
    VocabItem(word:"カレー【ライス】",reading:"karee [raisu]",meaning:"তরকারি [ভাত]"),
    VocabItem(word:"アイスクリーム",reading:"aisukuriimu",meaning:"আইসক্রিম"),
    VocabItem(word:"切手",reading:"kitte",meaning:"ডাকটিকেট"),
    VocabItem(word:"葉書",reading:"hagaki",meaning:"পোস্টকার্ড"),
    VocabItem(word:"封筒",reading:"fuutou",meaning:"খাম"),
    VocabItem(word:"両親",reading:"ryoushin",meaning:"পিতা-মাতা"),
    VocabItem(word:"兄弟",reading:"kyoudai",meaning:"ভাই-বোন"),
    VocabItem(word:"兄",reading:"ani",meaning:"নিজের বড় ভাই"),
    VocabItem(word:"お兄さん",reading:"oniisan",meaning:"অন্যের বড় ভাই"),
    VocabItem(word:"姉",reading:"ane",meaning:"নিজের বড় বোন"),
    VocabItem(word:"お姉さん",reading:"oneesan",meaning:"অন্যের বড় বোন"),
    VocabItem(word:"弟",reading:"otouto",meaning:"নিজের ছোট ভাই"),
    VocabItem(word:"弟さん",reading:"otoutosan",meaning:"অন্যের ছোট ভাই"),
    VocabItem(word:"妹",reading:"imouto",meaning:"নিজের ছোট বোন"),
    VocabItem(word:"妹さん",reading:"imoutosan",meaning:"অন্যের ছোট বোন"),
    VocabItem(word:"外国",reading:"gaikoku",meaning:"বিদেশ"),
    VocabItem(word:"留学生",reading:"ryuugakusei",meaning:"বিদেশি শিক্ষার্থী"),
    VocabItem(word:"クラス",reading:"kurasu",meaning:"ক্লাস"),
    VocabItem(word:"~時間",reading:"~jikan",meaning:"~ঘন্টা"),
    VocabItem(word:"~週間",reading:"~shuukan",meaning:"~সপ্তাহ"),
    VocabItem(word:"~か月",reading:"~kagetsu",meaning:"~মাস"),
    VocabItem(word:"~年",reading:"~nen",meaning:"~বছর"),
    VocabItem(word:"〜ぐらい",reading:"~gurai",meaning:"প্রায়"),
    VocabItem(word:"どのくらい",reading:"donokurai",meaning:"কতক্ষণ"),
    VocabItem(word:"ぜんぶで",reading:"zenbude",meaning:"সর্বমোট"),
    VocabItem(word:"みんな",reading:"minna",meaning:"সকল"),
    VocabItem(word:"~だけ",reading:"~dake",meaning:"শুধুমাত্র"),
    VocabItem(word:"かしこまりました",reading:"kashikomarimashita",meaning:"অবশ্যই"),
    VocabItem(word:"会話",reading:"kaiwa",meaning:"কথা-বার্তা"),
    VocabItem(word:"いい天気ですね",reading:"ii tenki desu ne",meaning:"সুন্দর আবহাওয়া"),
    VocabItem(word:"お出かけですか",reading:"odekake desu ka",meaning:"বাইরে যাচ্ছেন?"),
    VocabItem(word:"行ってまいります",reading:"itte mairimasu",meaning:"গিয়ে আসবো"),
    VocabItem(word:"ちょっと〜まで",reading:"chotto ~ made",meaning:"একটু ~ পর্যন্ত"),
    VocabItem(word:"行っていらっしゃい",reading:"itte irasshai",meaning:"গিয়ে আসুন"),
    VocabItem(word:"船便",reading:"funabin",meaning:"সমুদ্র মেইল"),
    VocabItem(word:"エアメール【航空便】",reading:"eameeru [koukuubin]",meaning:"এয়ারমেইল"),
    VocabItem(word:"お願いします",reading:"onegaishimasu",meaning:"দয়া করে"),
    VocabItem(word:"オーストラリア",reading:"oosutoraria",meaning:"অস্ট্রেলিয়া"),
  ],
  12: [
    VocabItem(word:"遊びます",reading:"asobimasu",meaning:"খেলা করা"),
    VocabItem(word:"泳ぎます",reading:"oyogimasu",meaning:"সাঁতার কাটা"),
    VocabItem(word:"迎えます",reading:"mukaえます",meaning:"সাক্ষাৎ করতে যাওয়া"),
    VocabItem(word:"疲れます",reading:"tsukaremasu",meaning:"ক্লান্ত হওয়া"),
    VocabItem(word:"結婚します",reading:"kekkonshimasu",meaning:"বিয়ে করা"),
    VocabItem(word:"買い物します",reading:"kaimonoshimasu",meaning:"কেনাকাটা করা"),
    VocabItem(word:"食事します",reading:"shokujishimasu",meaning:"খাবার খাওয়া"),
    VocabItem(word:"散歩します",reading:"sanposhimasu [kouen o~]",meaning:"হাঁটাহাটি করা"),
    VocabItem(word:"大変[な]",reading:"taihen [na]",meaning:"কঠিন"),
    VocabItem(word:"欲しい",reading:"hoshii",meaning:"চাওয়া"),
    VocabItem(word:"広い",reading:"hiroi",meaning:"প্রশস্ত"),
    VocabItem(word:"狭い",reading:"semai",meaning:"সরু"),
    VocabItem(word:"プール",reading:"puuru",meaning:"সুইমিং পুল"),
    VocabItem(word:"川",reading:"kawa",meaning:"নদী"),
    VocabItem(word:"美術",reading:"bijutsu",meaning:"চারুকলা"),
    VocabItem(word:"釣り",reading:"tsuri",meaning:"মাছ ধরা"),
    VocabItem(word:"スキー",reading:"sukii",meaning:"স্কি"),
    VocabItem(word:"週末",reading:"shuumatsu",meaning:"সপ্তাহান্ত"),
    VocabItem(word:"お正月",reading:"oshougatsu",meaning:"নববর্ষ"),
    VocabItem(word:"~ごろ",reading:"~goro",meaning:"প্রায়"),
    VocabItem(word:"なにか",reading:"nanika",meaning:"কিছু"),
    VocabItem(word:"どこか",reading:"dokoka",meaning:"কোথাও"),
    VocabItem(word:"練習",reading:"renshuu",meaning:"অনুশীলনী"),
    VocabItem(word:"のどがかわきました",reading:"nodo ga kawakimashita",meaning:"তৃষ্ণার্ত"),
    VocabItem(word:"おなかがすきました",reading:"onaka ga sukimashita",meaning:"ক্ষুধার্ত"),
    VocabItem(word:"おなかがいっぱいです",reading:"onaka ga ippai desu",meaning:"পেট ভর্তি"),
    VocabItem(word:"そうしましょう",reading:"sou shimashou",meaning:"করা যাক"),
    VocabItem(word:"会話",reading:"kaiwa",meaning:"কথা-বার্তা"),
    VocabItem(word:"ご注文は?",reading:"go-chuumon wa?",meaning:"অর্ডার নিতে পারি?"),
    VocabItem(word:"定食",reading:"teishoku",meaning:"সেট খাবার"),
    VocabItem(word:"牛どん",reading:"gyuudon",meaning:"গরুর মাংসের বাটি"),
    VocabItem(word:"少々お待ちください",reading:"shoushou omachi kudasai",meaning:"একটু অপেক্ষা করুন"),
    VocabItem(word:"〜でございます",reading:"~de gozaimasu",meaning:"সের এর ভদ্র ভাষা"),
    VocabItem(word:"別々に",reading:"betsubetsu ni",meaning:"আলাদাভাবে"),
    VocabItem(word:"アキックス",reading:"akikkusu",meaning:"আকিক্স"),
    VocabItem(word:"おはようテレビ",reading:"ohayou terebi",meaning:"ওহায়ো টিভি"),
  ],
  13: [
    VocabItem(word:"点けます",reading:"tsukemasu",meaning:"জ্বালানো"),
    VocabItem(word:"消します",reading:"keshimasu",meaning:"নিভানো"),
    VocabItem(word:"開けます",reading:"akemasu",meaning:"খোলা"),
    VocabItem(word:"閉めます",reading:"shimemasu",meaning:"বন্ধ করা"),
    VocabItem(word:"急ぎます",reading:"isogimasu",meaning:"তাড়াহুড়া করা"),
    VocabItem(word:"待ちます",reading:"machimasu",meaning:"অপেক্ষা করা"),
    VocabItem(word:"持ちます",reading:"mochimasu",meaning:"ধরা"),
    VocabItem(word:"取ります",reading:"torimasu",meaning:"তোলা"),
    VocabItem(word:"手伝います",reading:"tetsudaimasu",meaning:"সাহায্য করা"),
    VocabItem(word:"呼びます",reading:"yobimasu",meaning:"ডাকা"),
    VocabItem(word:"話します",reading:"hanashimasu",meaning:"কথা বলা"),
    VocabItem(word:"使います",reading:"tsukaimasu",meaning:"ব্যবহার করা"),
    VocabItem(word:"止めます",reading:"tomemasu",meaning:"থামানো"),
    VocabItem(word:"見せます",reading:"misemasu",meaning:"দেখানো"),
    VocabItem(word:"教えます",reading:"oshiemasu",meaning:"শিখানো/বলে দেওয়া"),
    VocabItem(word:"座ります",reading:"suwarimasu",meaning:"বসা"),
    VocabItem(word:"立ちます",reading:"tachimasu",meaning:"দাঁড়ানো"),
    VocabItem(word:"入ります",reading:"hairimasu",meaning:"প্রবেশ করা"),
    VocabItem(word:"出ます",reading:"demasu",meaning:"বের হওয়া"),
    VocabItem(word:"降ります",reading:"furimasu",meaning:"বৃষ্টি পড়া"),
    VocabItem(word:"コピーします",reading:"kopiishimasu",meaning:"কপি করা"),
    VocabItem(word:"電気",reading:"denki",meaning:"বিদ্যুৎ"),
    VocabItem(word:"エアコン",reading:"eakon",meaning:"এয়ার কন্ডিশনার"),
    VocabItem(word:"パスポート",reading:"pasupooto",meaning:"পাসপোর্ট"),
    VocabItem(word:"名前",reading:"namae",meaning:"নাম"),
    VocabItem(word:"住所",reading:"juusho",meaning:"ঠিকানা"),
    VocabItem(word:"地図",reading:"chizu",meaning:"মানচিত্র"),
    VocabItem(word:"塩",reading:"shio",meaning:"লবণ"),
    VocabItem(word:"砂糖",reading:"satou",meaning:"চিনি"),
    VocabItem(word:"問題",reading:"mondai",meaning:"প্রশ্ন"),
    VocabItem(word:"答え",reading:"kotae",meaning:"উত্তর"),
    VocabItem(word:"読み方",reading:"yomikata",meaning:"পড়ার পদ্ধতি"),
    VocabItem(word:"まっすぐ",reading:"massugu",meaning:"সোজা"),
    VocabItem(word:"ゆっくり",reading:"yukkuri",meaning:"ধীরে ধীরে"),
    VocabItem(word:"早く",reading:"hayaku",meaning:"দ্রুত"),
    VocabItem(word:"また",reading:"mata",meaning:"আবার"),
    VocabItem(word:"あとで",reading:"atode",meaning:"পরে"),
    VocabItem(word:"もうすこし",reading:"mousukoshi",meaning:"আরও একটু"),
    VocabItem(word:"もう〜",reading:"mou ~",meaning:"আরও"),
    VocabItem(word:"練習",reading:"renshuu",meaning:"অনুশীলনী"),
    VocabItem(word:"さあ",reading:"saa",meaning:"সা"),
    VocabItem(word:"あれ?",reading:"are?",meaning:"আরে?"),
    VocabItem(word:"会話",reading:"kaiwa",meaning:"কথা-বার্তা"),
    VocabItem(word:"しんごうをみぎへまがってください",reading:"shingou o migi e magatte kudasai",meaning:"সিগন্যালে ডান দিকে ঘুরুন"),
    VocabItem(word:"これでおねがいします",reading:"kore de onegaishimasu",meaning:"এটা দিয়ে দেন"),
    VocabItem(word:"お釣り",reading:"otsuri",meaning:"ফেরত টাকা"),
    VocabItem(word:"うめだ",reading:"umeda",meaning:"উমেদা"),
    VocabItem(word:"みどりちょう",reading:"midorichou",meaning:"মিদোরিচো"),
  ],
  14: [
    VocabItem(word:"置きます",reading:"okimasu",meaning:"রাখা"),
    VocabItem(word:"作ります",reading:"tsukurimasu",meaning:"তৈরি করা"),
    VocabItem(word:"売ります",reading:"urimasu",meaning:"বিক্রি করা"),
    VocabItem(word:"知ります",reading:"shirimasu",meaning:"জানা"),
    VocabItem(word:"住みます",reading:"sumimasu",meaning:"বসবাস করা"),
    VocabItem(word:"研究します",reading:"kenkyuushimasu",meaning:"গবেষণা করা"),
    VocabItem(word:"資料",reading:"shiryou",meaning:"নথিপত্র"),
    VocabItem(word:"カタログ",reading:"katarogu",meaning:"তালিকা"),
    VocabItem(word:"時刻表",reading:"jikokuhyou",meaning:"সময়সূচী"),
    VocabItem(word:"服",reading:"fuku",meaning:"পোশাক"),
    VocabItem(word:"製品",reading:"seihin",meaning:"পণ্য"),
    VocabItem(word:"ソフト",reading:"sofutowa",meaning:"সফটওয়্যার"),
    VocabItem(word:"電子辞書",reading:"denshijisho",meaning:"ইলেকট্রনিক অভিধান"),
    VocabItem(word:"経済",reading:"keizai",meaning:"অর্থনীতি"),
    VocabItem(word:"市役所",reading:"shiyakusho",meaning:"সিটি অফিস"),
    VocabItem(word:"高校",reading:"koukou",meaning:"কলেজ"),
    VocabItem(word:"歯医者",reading:"haisha",meaning:"দাঁতের ডাক্তার"),
    VocabItem(word:"独身",reading:"dokushin",meaning:"অবিবাহিত"),
    VocabItem(word:"すみません",reading:"sumimasen",meaning:"মাফ করবেন"),
    VocabItem(word:"練習",reading:"renshuu",meaning:"অনুশীলনী"),
    VocabItem(word:"皆さん",reading:"minasan",meaning:"সকল"),
    VocabItem(word:"会話",reading:"kaiwa",meaning:"কথা-বার্তা"),
    VocabItem(word:"思い出します",reading:"omoidashimasu",meaning:"মনে করা"),
    VocabItem(word:"いらっしゃいます",reading:"irasshaimasu",meaning:"আছেন (সম্মান)"),
    VocabItem(word:"日本橋",reading:"nipponbashi",meaning:"নিপ্পনবাশি"),
    VocabItem(word:"みんなのインタビ",reading:"minna no intabyu",meaning:"মিন্না নো ইন্টাভিউ"),
  ],
  15: [
    VocabItem(word:"乗ります",reading:"norimasu",meaning:"চড়া"),
    VocabItem(word:"降ります",reading:"orimasu",meaning:"নামা"),
    VocabItem(word:"乗り換えます",reading:"norikaemasu",meaning:"পরিবর্তন করা"),
    VocabItem(word:"浴びます",reading:"abimasu",meaning:"গোসল করা"),
    VocabItem(word:"入れます",reading:"iremasu",meaning:"ঢোকানো"),
    VocabItem(word:"出します",reading:"dashimasu",meaning:"বের করা"),
    VocabItem(word:"下ろします",reading:"oroshimasu",meaning:"তোলা"),
    VocabItem(word:"入ります",reading:"hairimasu",meaning:"ভর্তি হওয়া"),
    VocabItem(word:"出ます",reading:"demasu",meaning:"স্নাতক হওয়া"),
    VocabItem(word:"押します",reading:"oshimasu",meaning:"চাপ দেওয়া"),
    VocabItem(word:"飲みます",reading:"nomimasu",meaning:"পান করা"),
    VocabItem(word:"始めます",reading:"hajimemasu",meaning:"শুরু করা"),
    VocabItem(word:"見学します",reading:"kengakushimasu",meaning:"শিক্ষা সফর"),
    VocabItem(word:"電話します",reading:"denwashimasu",meaning:"টেলিফোন করা"),
    VocabItem(word:"若い",reading:"wakai",meaning:"তরুণ"),
    VocabItem(word:"長い",reading:"nagai",meaning:"লম্বা"),
    VocabItem(word:"短い",reading:"mijikai",meaning:"খাটো"),
    VocabItem(word:"明るい",reading:"akarui",meaning:"উজ্জ্বল"),
    VocabItem(word:"暗い",reading:"kurai",meaning:"অন্ধকার"),
    VocabItem(word:"体",reading:"karada",meaning:"শরীর"),
    VocabItem(word:"頭",reading:"atama",meaning:"মাথা"),
    VocabItem(word:"髪",reading:"kami",meaning:"চুল"),
    VocabItem(word:"顔",reading:"kao",meaning:"মুখ"),
    VocabItem(word:"目",reading:"me",meaning:"চোখ"),
    VocabItem(word:"耳",reading:"mimi",meaning:"কান"),
    VocabItem(word:"鼻",reading:"hana",meaning:"নাক"),
    VocabItem(word:"口",reading:"kuchi",meaning:"মুখ"),
    VocabItem(word:"歯",reading:"ha",meaning:"দাঁত"),
    VocabItem(word:"お腹",reading:"onaka",meaning:"পেট"),
    VocabItem(word:"足",reading:"ashi",meaning:"পা"),
    VocabItem(word:"背",reading:"se",meaning:"উচ্চতা"),
    VocabItem(word:"サービス",reading:"saabisu",meaning:"সেবা"),
    VocabItem(word:"ジョギング",reading:"jogingu",meaning:"জগিং"),
    VocabItem(word:"シャワー",reading:"shawaa",meaning:"গোসল"),
    VocabItem(word:"緑",reading:"midori",meaning:"সবুজ"),
    VocabItem(word:"お寺",reading:"otera",meaning:"বৌদ্ধ মন্দির"),
    VocabItem(word:"神社",reading:"jinja",meaning:"শিনতো মন্দির"),
    VocabItem(word:"一番",reading:"ichiban",meaning:"~ নং"),
    VocabItem(word:"どうやって",reading:"douyatte",meaning:"কিভাবে"),
    VocabItem(word:"どの~",reading:"dono ~",meaning:"কোনটা"),
    VocabItem(word:"どれ",reading:"dore",meaning:"কোনটি"),
    VocabItem(word:"練習",reading:"renshuu",meaning:"অনুশীলনী"),
    VocabItem(word:"すごいですね",reading:"sugoi desu ne",meaning:"দারুণ!"),
    VocabItem(word:"[いいえ。]まだまだです",reading:"[iie.] madamada desu",meaning:"এখনো অনেক বাকি"),
    VocabItem(word:"会話",reading:"kaiwa",meaning:"কথা-বার্তা"),
    VocabItem(word:"おひきだしですか",reading:"ohikidashi desu ka",meaning:"টাকা তুলবেন?"),
    VocabItem(word:"まず",reading:"mazu",meaning:"সবার আগে"),
    VocabItem(word:"次に",reading:"tsugi ni",meaning:"তারপর"),
    VocabItem(word:"キャッシュカード",reading:"kyasshukaado",meaning:"নগদ কার্ড"),
    VocabItem(word:"暗証番号",reading:"anshoubangou",meaning:"পিন"),
    VocabItem(word:"金額",reading:"kingaku",meaning:"টাকার পরিমাণ"),
    VocabItem(word:"確認",reading:"kakunin",meaning:"নিশ্চিতকরণ"),
    VocabItem(word:"ボタン",reading:"botan",meaning:"বোতাম"),
    VocabItem(word:"JR",reading:"JR",meaning:"জেআর"),
    VocabItem(word:"雪祭り",reading:"yukimatsuri",meaning:"তুষার উৎসব"),
    VocabItem(word:"バンドン",reading:"bandon",meaning:"বান্দুং"),
    VocabItem(word:"フランケン",reading:"furanken",meaning:"ফ্রাঙ্কেন"),
    VocabItem(word:"ベラクルス",reading:"berakurusu",meaning:"ভেরাক্রুজ"),
    VocabItem(word:"うめだ",reading:"umeda",meaning:"উমেদা"),
    VocabItem(word:"大学前",reading:"daigakumae",meaning:"বিশ্ববিদ্যালয়ের সামনে"),
  ],
  16: [
    VocabItem(word:"覚えます",reading:"oboemasu",meaning:"মনে রাখা"),
    VocabItem(word:"忘れます",reading:"wasuremasu",meaning:"ভুলে যাওয়া"),
    VocabItem(word:"無くします",reading:"nakushimasu",meaning:"হারানো"),
    VocabItem(word:"払います",reading:"haraimasu",meaning:"পরিশোধ করা"),
    VocabItem(word:"返します",reading:"kaeshimasu",meaning:"ফিরিয়ে দেওয়া"),
    VocabItem(word:"出かけます",reading:"dekakemasu",meaning:"বাইরে যাওয়া"),
    VocabItem(word:"脱ぎます",reading:"nugimasu",meaning:"খুলে ফেলা"),
    VocabItem(word:"持って行きます",reading:"motteikimasu",meaning:"নিয়ে যাওয়া"),
    VocabItem(word:"持って来ます",reading:"mottekimasu",meaning:"নিয়ে আসা"),
    VocabItem(word:"心配します",reading:"shinpaishimasu",meaning:"দুশ্চিন্তা করা"),
    VocabItem(word:"残業します",reading:"zangyoushimasu",meaning:"অতিরিক্ত কাজ করা"),
    VocabItem(word:"出張します",reading:"shucchoushimasu",meaning:"ব্যবসা ভ্রমণ"),
    VocabItem(word:"飲みます[くすりを~]",reading:"nomimasu [kusuri o~]",meaning:"ঔষধ খাওয়া"),
    VocabItem(word:"入ります[おふろに~]",reading:"hairimasu [ofuro ni~]",meaning:"গোসল করা"),
    VocabItem(word:"大切[な]",reading:"taisetsu [na]",meaning:"গুরুত্বপূর্ণ"),
    VocabItem(word:"大丈夫[な]",reading:"daijoubu [na]",meaning:"ঠিক আছে"),
    VocabItem(word:"危ない",reading:"abunai",meaning:"বিপজ্জনক"),
    VocabItem(word:"禁煙",reading:"kinen",meaning:"ধূমপান নিষিদ্ধ"),
    VocabItem(word:"保険証",reading:"hokenshou",meaning:"বীমা কার্ড"),
    VocabItem(word:"熱",reading:"netsu",meaning:"জ্বর"),
    VocabItem(word:"病気",reading:"byouki",meaning:"অসুখ"),
    VocabItem(word:"薬",reading:"kusuri",meaning:"ঔষধ"),
    VocabItem(word:"お風呂",reading:"ofuro",meaning:"গোসল"),
    VocabItem(word:"上着",reading:"uwagi",meaning:"জ্যাকেট"),
    VocabItem(word:"下着",reading:"shitagi",meaning:"অন্তর্বাস"),
    VocabItem(word:"~までに",reading:"~ madeni",meaning:"~ এর মধ্যে"),
    VocabItem(word:"ですから",reading:"desukara",meaning:"সেজন্য"),
    VocabItem(word:"会話",reading:"kaiwa",meaning:"কথা-বার্তা"),
    VocabItem(word:"どうしましたか",reading:"dou shimashita ka",meaning:"কি হয়েছে?"),
    VocabItem(word:"のどがいたいです",reading:"nodo ga itai desu",meaning:"গলা ব্যথা"),
    VocabItem(word:"風邪",reading:"kaze",meaning:"ঠান্ডা লাগা"),
    VocabItem(word:"それから",reading:"sorekara",meaning:"তারপর"),
    VocabItem(word:"お大事に",reading:"odaijini",meaning:"সুস্থ থাকুন"),
  ],
  17: [
    VocabItem(word:"できます",reading:"dekimasu",meaning:"করতে পারা"),
    VocabItem(word:"洗います",reading:"araimasu",meaning:"ধোয়া"),
    VocabItem(word:"引きます",reading:"hikimasu",meaning:"বাজানো"),
    VocabItem(word:"歌います",reading:"utaimasu",meaning:"গান গাওয়া"),
    VocabItem(word:"集めます",reading:"atsumemasu",meaning:"সংগ্রহ করা"),
    VocabItem(word:"捨てます",reading:"sutemasu",meaning:"ফেলা"),
    VocabItem(word:"変えます",reading:"kaemasu",meaning:"পরিবর্তন করা"),
    VocabItem(word:"運転します",reading:"untenshimasu",meaning:"চালানো"),
    VocabItem(word:"予約します",reading:"yoyakushimasu",meaning:"সংরক্ষণ করা"),
    VocabItem(word:"ピアノ",reading:"piano",meaning:"পিয়ানো"),
    VocabItem(word:"ーメートル",reading:"~ meetoru",meaning:"মিটার"),
    VocabItem(word:"現金",reading:"genkin",meaning:"নগদ"),
    VocabItem(word:"趣味",reading:"shumi",meaning:"শখ"),
    VocabItem(word:"日記",reading:"nikki",meaning:"ডায়েরি"),
    VocabItem(word:"お祈り",reading:"oinori",meaning:"প্রার্থনা"),
    VocabItem(word:"課長",reading:"kachou",meaning:"সেকশন প্রধান"),
    VocabItem(word:"部長",reading:"buchou",meaning:"বিভাগ প্রধান"),
    VocabItem(word:"社長",reading:"shachou",meaning:"কোম্পানির মালিক"),
    VocabItem(word:"動物",reading:"doubutsu",meaning:"প্রাণী"),
    VocabItem(word:"馬",reading:"uma",meaning:"ঘোড়া"),
    VocabItem(word:"インターネット",reading:"intaanetto",meaning:"ইন্টারনেট"),
    VocabItem(word:"会話",reading:"kaiwa",meaning:"কথা-বার্তা"),
    VocabItem(word:"とくに",reading:"tokuni",meaning:"বিশেষ করে"),
    VocabItem(word:"へえ",reading:"hee",meaning:"সত্যি"),
    VocabItem(word:"それはおもしろいですね",reading:"sore wa omoshiroi desu ne",meaning:"এটা মজার"),
    VocabItem(word:"なかなか",reading:"nakanaka",meaning:"সহজে না"),
    VocabItem(word:"ほんとうですか",reading:"hontou desu ka",meaning:"সত্যি?"),
    VocabItem(word:"ぜひ",reading:"zehi",meaning:"অবশ্যই"),
    VocabItem(word:"ふるさと",reading:"furusato",meaning:"ফুরুসাতো"),
    VocabItem(word:"ビートルズ",reading:"biitoruzu",meaning:"বিটলস"),
    VocabItem(word:"あきはばら",reading:"akihabara",meaning:"আকিহাবারা"),
  ],
  18: [
    VocabItem(word:"上ります",reading:"noborimasu",meaning:"আরোহণ করা"),
    VocabItem(word:"泊まります",reading:"tomarimasu",meaning:"থাকা"),
    VocabItem(word:"掃除します",reading:"soujishimasu",meaning:"পরিষ্কার করা"),
    VocabItem(word:"洗濯します",reading:"sentakushimasu",meaning:"কাপড় ধোয়া"),
    VocabItem(word:"なります",reading:"narimasu",meaning:"হওয়া"),
    VocabItem(word:"眠い",reading:"nemui",meaning:"ঘুমন্ত"),
    VocabItem(word:"強い",reading:"tsuyoi",meaning:"শক্তিশালী"),
    VocabItem(word:"弱い",reading:"yowai",meaning:"দুর্বল"),
    VocabItem(word:"練習",reading:"renshuu",meaning:"অনুশীলনী"),
    VocabItem(word:"ゴルフ",reading:"gorufu",meaning:"গলফ"),
    VocabItem(word:"相撲",reading:"sumou",meaning:"সুমো"),
    VocabItem(word:"お茶",reading:"ocha",meaning:"চা উৎসব"),
    VocabItem(word:"日",reading:"hi",meaning:"দিন"),
    VocabItem(word:"調子",reading:"choushi",meaning:"অবস্থা"),
    VocabItem(word:"一度",reading:"ichido",meaning:"একবার"),
    VocabItem(word:"一度も",reading:"ichidomo",meaning:"একবারও না"),
    VocabItem(word:"段々",reading:"dandan",meaning:"ধীরে ধীরে"),
    VocabItem(word:"もうすぐ",reading:"mousugu",meaning:"শীঘ্রই"),
    VocabItem(word:"おかげさまで",reading:"okagesamade",meaning:"আপনার দয়ায়"),
    VocabItem(word:"でも",reading:"demo",meaning:"কিন্তু"),
    VocabItem(word:"会話",reading:"kaiwa",meaning:"কথা-বার্তা"),
    VocabItem(word:"乾杯",reading:"kanpai",meaning:"চিয়ার্স"),
    VocabItem(word:"ダイエット",reading:"daietto",meaning:"ডায়েট"),
    VocabItem(word:"無理[な]",reading:"muri [na]",meaning:"অসম্ভব"),
    VocabItem(word:"体にいい",reading:"karada ni ii",meaning:"স্বাস্থ্যের জন্য ভালো"),
    VocabItem(word:"とうきょうスカイツリー",reading:"toukyou sukaitsurii",meaning:"টোকিও স্কাই ট্রি"),
    VocabItem(word:"かつしかほくさい",reading:"katsushika hokusai",meaning:"কাতসুশিকা হোকুসাই"),
  ],
  19: [
    VocabItem(word:"要ります",reading:"irimasu",meaning:"প্রয়োজন"),
    VocabItem(word:"調べます",reading:"shirabemasu",meaning:"অনুসন্ধান করা"),
    VocabItem(word:"修理します",reading:"shuurishimasu",meaning:"মেরামত করা"),
    VocabItem(word:"僕",reading:"boku",meaning:"আমি (informal)"),
    VocabItem(word:"君",reading:"kimi",meaning:"তুমি (informal)"),
    VocabItem(word:"~君",reading:"~ kun",meaning:"~কুন"),
    VocabItem(word:"うん",reading:"un",meaning:"হ্যাঁ (informal)"),
    VocabItem(word:"ううん",reading:"uun",meaning:"না (informal)"),
    VocabItem(word:"言葉",reading:"kotoba",meaning:"শব্দ"),
    VocabItem(word:"着物",reading:"kimono",meaning:"কিমোনো"),
    VocabItem(word:"ビザ",reading:"biza",meaning:"ভিসা"),
    VocabItem(word:"初め",reading:"hajime",meaning:"শুরু"),
    VocabItem(word:"終わり",reading:"owari",meaning:"শেষ"),
    VocabItem(word:"こっち",reading:"kocchi",meaning:"এইদিকে"),
    VocabItem(word:"そっち",reading:"socchi",meaning:"ওদিকে"),
    VocabItem(word:"あっち",reading:"acchi",meaning:"ঐদিকে"),
    VocabItem(word:"どっち",reading:"docchi",meaning:"কোনদিকে"),
    VocabItem(word:"皆で",reading:"minna de",meaning:"সবাই একসাথে"),
    VocabItem(word:"〜けど",reading:"~ kedo",meaning:"কিন্তু (informal)"),
    VocabItem(word:"おなかがいっぱいです",reading:"onaka ga ippai desu",meaning:"পেট ভরা"),
    VocabItem(word:"会話",reading:"kaiwa",meaning:"কথা-বার্তা"),
    VocabItem(word:"よかったら",reading:"yokattara",meaning:"পছন্দ করলে"),
    VocabItem(word:"色々[な]",reading:"iroiro [na]",meaning:"বিভিন্ন"),
  ],
  20: [
    VocabItem(word:"思います",reading:"omoimasu",meaning:"মনে করা"),
    VocabItem(word:"言います",reading:"iimasu",meaning:"বলা"),
    VocabItem(word:"勝ちます",reading:"kachimasu",meaning:"জয় লাভ করা"),
    VocabItem(word:"負けます",reading:"makemasu",meaning:"হারা"),
    VocabItem(word:"あります[おまつりが~]",reading:"arimasu",meaning:"অনুষ্ঠিত হওয়া"),
    VocabItem(word:"役に立ちます",reading:"yakunitachimasu",meaning:"উপকারী হওয়া"),
    VocabItem(word:"動きます",reading:"ugokimasu",meaning:"চলা"),
    VocabItem(word:"辞めます",reading:"yamemasu",meaning:"ছাড়া"),
    VocabItem(word:"気をつけます",reading:"ki o tsukemasu",meaning:"সতর্ক থাকা"),
    VocabItem(word:"留学します",reading:"ryuugakushimasu",meaning:"বিদেশে পড়া"),
    VocabItem(word:"無駄[な]",reading:"muda [na]",meaning:"অকেজো"),
    VocabItem(word:"不便[な]",reading:"fuben [na]",meaning:"অসুবিধাজনক"),
    VocabItem(word:"すごい",reading:"sugoi",meaning:"দুর্দান্ত"),
    VocabItem(word:"本当",reading:"hontou",meaning:"সত্য"),
    VocabItem(word:"嘘",reading:"uso",meaning:"মিথ্যা"),
    VocabItem(word:"自動車",reading:"jidousha",meaning:"গাড়ি"),
    VocabItem(word:"交通",reading:"koutsuu",meaning:"ট্রাফিক"),
    VocabItem(word:"物価",reading:"bukka",meaning:"মূল্য"),
    VocabItem(word:"放送",reading:"housou",meaning:"সম্প্রচার"),
    VocabItem(word:"ニュース",reading:"nyuusu",meaning:"সংবাদ"),
    VocabItem(word:"アニメ",reading:"anime",meaning:"অ্যানিমে"),
    VocabItem(word:"マンガ",reading:"manga",meaning:"কমিক"),
    VocabItem(word:"デザイン",reading:"dezain",meaning:"ডিজাইন"),
    VocabItem(word:"夢",reading:"yume",meaning:"স্বপ্ন"),
    VocabItem(word:"天才",reading:"tensai",meaning:"প্রতিভাবান"),
    VocabItem(word:"試合",reading:"shiai",meaning:"খেলা"),
    VocabItem(word:"意見",reading:"iken",meaning:"মতামত"),
    VocabItem(word:"話",reading:"hanashi",meaning:"কথা"),
    VocabItem(word:"地球",reading:"chikyuu",meaning:"পৃথিবী"),
    VocabItem(word:"月",reading:"tsuki",meaning:"চাঁদ"),
    VocabItem(word:"最近",reading:"saikin",meaning:"ইদানিং"),
    VocabItem(word:"多分",reading:"tabun",meaning:"হতে পারে"),
    VocabItem(word:"きっと",reading:"kitto",meaning:"অবশ্যই"),
    VocabItem(word:"そんなに",reading:"sonnani",meaning:"তেমন না"),
    VocabItem(word:"ほんとうに",reading:"hontouni",meaning:"সত্যিই"),
    VocabItem(word:"~について",reading:"~ ni tsuite",meaning:"~ সম্পর্কে"),
    VocabItem(word:"会話",reading:"kaiwa",meaning:"কথা-বার্তা"),
    VocabItem(word:"ひさしぶりです",reading:"hisashiburi desu",meaning:"অনেক দিন পর"),
    VocabItem(word:"~でものみませんか",reading:"~ demo nomimasen ka",meaning:"~ পান করবেন?"),
    VocabItem(word:"もちろん",reading:"mochiron",meaning:"অবশ্যই"),
    VocabItem(word:"もうかえらないと",reading:"mou kaeranaito",meaning:"এখন বাড়ি ফিরতে হবে"),
    VocabItem(word:"アインシュタイン",reading:"ainshutain",meaning:"আইনস্টাইন"),
    VocabItem(word:"ガガーリン",reading:"gagaarin",meaning:"গাগারিন"),
    VocabItem(word:"ガリレオ",reading:"garireo",meaning:"গ্যালিলিও"),
    VocabItem(word:"キングぼく",reading:"kingu boku",meaning:"মার্টিন লুথার কিং"),
    VocabItem(word:"フランクリン",reading:"furankurin",meaning:"ফ্র্যাঙ্কলিন"),
    VocabItem(word:"かぐやひめ",reading:"kaguyahime",meaning:"কাগুয়া হিমে"),
    VocabItem(word:"てんじんまつり",reading:"tenjin matsuri",meaning:"তেনজিন উৎসব"),
    VocabItem(word:"よしのやま",reading:"yoshinoyama",meaning:"ইয়োশিনো পর্বত"),
    VocabItem(word:"カンガルー",reading:"kangaruu",meaning:"ক্যাঙ্গারু"),
    VocabItem(word:"キャプテン・クック",reading:"kyaputen kukku",meaning:"ক্যাপ্টেন কুক"),
    VocabItem(word:"ヨーネン",reading:"younen",meaning:"ইয়োনেন"),
  ],
  21: [
    VocabItem(word:"聞きます[先生に~]",reading:"kikimasu [sensei ni ~]",meaning:"জিজ্ঞাসা করা"),
    VocabItem(word:"回します",reading:"mawashimasu",meaning:"মোড় নেয়া"),
    VocabItem(word:"引きます",reading:"hikimasu",meaning:"টান দেওয়া"),
    VocabItem(word:"変えます",reading:"kaemasu",meaning:"পরিবর্তন করা"),
    VocabItem(word:"触ります[ドアに~]",reading:"sawarimasu [doa ni ~]",meaning:"স্পর্শ করা"),
    VocabItem(word:"出ます[おつりが~]",reading:"demasu [otsuri ga ~]",meaning:"পরিবর্তন আসা"),
    VocabItem(word:"歩きます[みちを~]",reading:"arukimasu [michi o ~]",meaning:"হাঁটা"),
    VocabItem(word:"渡ります[はしを~]",reading:"watarimasu [hashi o ~]",meaning:"পার হওয়া"),
    VocabItem(word:"寂しい",reading:"sabishii",meaning:"একাকী"),
    VocabItem(word:"お湯",reading:"oyu",meaning:"গরম পানি"),
    VocabItem(word:"音",reading:"oto",meaning:"শব্দ"),
    VocabItem(word:"サイズ",reading:"saizu",meaning:"সাইজ"),
    VocabItem(word:"故障",reading:"koshou",meaning:"ভেঙ্গে পড়া"),
    VocabItem(word:"道",reading:"michi",meaning:"রাস্তা"),
    VocabItem(word:"交差点",reading:"kousaten",meaning:"ক্রসরোড"),
    VocabItem(word:"信号",reading:"shingou",meaning:"ট্রাফিক সিগন্যাল"),
    VocabItem(word:"角",reading:"kado",meaning:"কর্ণার"),
    VocabItem(word:"橋",reading:"hashi",meaning:"ব্রিজ"),
    VocabItem(word:"駐車場",reading:"chuushajou",meaning:"পার্কিং এলাকা"),
    VocabItem(word:"建物",reading:"tatemono",meaning:"বিল্ডিং"),
    VocabItem(word:"何回も",reading:"nankaimo",meaning:"অনেক বার"),
    VocabItem(word:"~目",reading:"~ me",meaning:"~নাম্বার"),
    VocabItem(word:"聖徳太子",reading:"shoutoku taishi",meaning:"প্রিন্স শোতোকু"),
    VocabItem(word:"法隆寺",reading:"houryuuji",meaning:"হোরিয়্যুজি মন্দির"),
    VocabItem(word:"元気茶",reading:"genkicha",meaning:"স্বাস্থ্য চা"),
    VocabItem(word:"本田駅",reading:"honda eki",meaning:"হন্ডা স্টেশন"),
    VocabItem(word:"図書館前",reading:"toshokanmae",meaning:"লাইব্রেরির সামনে"),
  ],
  22: [
    VocabItem(word:"くれます",reading:"kuremasu",meaning:"দেয়া (আমাকে)"),
    VocabItem(word:"直します",reading:"naoshimasu",meaning:"মেরামত করা"),
    VocabItem(word:"連れて行きます",reading:"tsureteikimasu",meaning:"নিয়ে যাওয়া"),
    VocabItem(word:"連れて来ます",reading:"tsuretekimasu",meaning:"নিয়ে আসা"),
    VocabItem(word:"送ります[ひとを~]",reading:"okurimasu [hito o ~]",meaning:"সাথে যাওয়া"),
    VocabItem(word:"紹介します",reading:"shoukaishimasu",meaning:"পরিচয় করানো"),
    VocabItem(word:"案内します",reading:"annaishimasu",meaning:"দেখানো"),
    VocabItem(word:"説明します",reading:"setsumeishimasu",meaning:"ব্যাখ্যা করা"),
    VocabItem(word:"おじいさん",reading:"ojiisan",meaning:"দাদা"),
    VocabItem(word:"おじいちゃん",reading:"ojiichan",meaning:"দাদা"),
    VocabItem(word:"おばあさん",reading:"obaasan",meaning:"দাদী"),
    VocabItem(word:"おばあちゃん",reading:"obaachan",meaning:"দাদী"),
    VocabItem(word:"準備",reading:"junbi",meaning:"প্রস্তুতি"),
    VocabItem(word:"引っ越し",reading:"hikkoshi",meaning:"বাড়ি পরিবর্তন"),
    VocabItem(word:"お菓子",reading:"okashi",meaning:"মিষ্টি"),
    VocabItem(word:"ホームステイ",reading:"hoomustei",meaning:"হোমস্টে"),
    VocabItem(word:"全部",reading:"zenbu",meaning:"সব"),
    VocabItem(word:"自分で",reading:"jibun de",meaning:"নিজে নিজে"),
    VocabItem(word:"他に",reading:"hokani",meaning:"এছাড়াও"),
    VocabItem(word:"母の日",reading:"haha no hi",meaning:"মা দিবস"),
  ],
  23: [
    VocabItem(word:"考えます",reading:"kangaemasu",meaning:"চিন্তা করা"),
    VocabItem(word:"着きます[えきに~]",reading:"tsukimasu [eki ni ~]",meaning:"পৌঁছানো"),
    VocabItem(word:"取ります[としを~]",reading:"torimasu [toshi o ~]",meaning:"বয়স বাড়া"),
    VocabItem(word:"足ります",reading:"tarimasu",meaning:"যথেষ্ট হওয়া"),
    VocabItem(word:"田舎",reading:"inaka",meaning:"গ্রামের বাড়ি"),
    VocabItem(word:"大使館",reading:"taishikan",meaning:"এম্বাসি"),
    VocabItem(word:"チャンス",reading:"chansu",meaning:"সুযোগ"),
    VocabItem(word:"億",reading:"oku",meaning:"শত মিলিয়ন"),
    VocabItem(word:"もし[~たら]",reading:"moshi [~ tara]",meaning:"যদি"),
    VocabItem(word:"意味",reading:"imi",meaning:"অর্থ"),
    VocabItem(word:"練習",reading:"renshuu",meaning:"অনুশীলনী"),
    VocabItem(word:"もしもし",reading:"moshimoshi",meaning:"হ্যালো (ফোন)"),
    VocabItem(word:"会話",reading:"kaiwa",meaning:"কথা-বার্তা"),
    VocabItem(word:"転勤",reading:"tenkin",meaning:"স্থানান্তর"),
    VocabItem(word:"事",reading:"koto",meaning:"জিনিস"),
    VocabItem(word:"暇",reading:"hima",meaning:"অবসর"),
    VocabItem(word:"色々お世話になりました",reading:"iroiro osewa ni narimashita",meaning:"আপনার সাহায্যের জন্য ধন্যবাদ"),
    VocabItem(word:"頑張ります",reading:"ganbarimasu",meaning:"সর্বোচ্চ চেষ্টা করা"),
    VocabItem(word:"どうぞお元気で",reading:"douzo ogenki de",meaning:"সুস্থ থাকুন"),
    VocabItem(word:"ベトナム",reading:"betonamu",meaning:"ভিয়েতনাম"),
  ],
};

final Map<int, List<GrammarItem>> grammarData = {
  1: [
    GrammarItem(pattern:"[N1] は [N2] です",explanation:"N1 হয় N2। সাধারণ পরিচয় দিতে ব্যবহৃত হয়। 'は' (wa) হলো টপিক মার্কার।",example:"わたし は タニヤ です (আমি তানিয়া।)"),
    GrammarItem(pattern:"[N1] は [N2] じゃありません",explanation:"'です' এর নেতিবাচক রূপ। (Formal: では ありません)",example:"わたし は がくせい じゃありません (আমি ছাত্র নই।)"),
    GrammarItem(pattern:"[Sentence] か",explanation:"বাক্যের শেষে 'か' যোগ করলে তা প্রশ্নবোধক হয়ে যায়।",example:"ミラーさん は かいしゃいん ですか (মি. মিরার কি কোম্পানি কর্মচারী?)"),
    GrammarItem(pattern:"[N] も",explanation:"'ও' (Also/Too) বোঝাতে 'は' এর বদলে 'も' বসে।",example:"サントスさん も ブラジルじん です (সান্তোস সাহেবও ব্রাজিলিয়ান।)"),
    GrammarItem(pattern:"[N1] の [N2]",explanation:"মালিকানা বা সম্পর্ক বোঝাতে 'の' (no) বসে।",example:"わたし の ほん (আমার বই।)"),
  ],
  2: [
    GrammarItem(pattern:"これ / それ / あれ",explanation:"বস্তু নির্দেশ করে। এটা (কাছে), ওটা (একটু দূরে), সেটা (অনেক দূরে)।",example:"বস্তু নির্দেশক সর্বনাম।"),
    GrammarItem(pattern:"この [N] / その [N] / あの [N]",explanation:"'এই বইটি' বা 'ঐ ব্যক্তিটি' এভাবে Noun এর সাথে নির্দিষ্ট করে বলতে ব্যবহৃত হয়।",example:"この ほん は わたし の です (এই বইটি আমার।)"),
    GrammarItem(pattern:"そう です / そう じゃありません",explanation:"'হ্যাঁ, তাই' অথবা 'না, তা নয়' সংক্ষেপে উত্তর দিতে।",example:"নিশ্চয়তা বা অস্বীকৃতি।"),
  ],
  3: [
    GrammarItem(pattern:"N1 は どこ ですか",explanation:"কোনো স্থান বা বস্তু কোথায় তা জিজ্ঞাসা করতে।",example:"しょくどう は どこ ですか (ক্যান্টিন কোথায়?)"),
    GrammarItem(pattern:"こちら/そちら/あちら",explanation:"এখানে/সেখানে/ঐখানে (মার্জিত রূপ)।",example:"エレベーター は あちら です (লিফট ঐদিকে।)"),
    GrammarItem(pattern:"ここ / そこ / あそこ",explanation:"স্থান নির্দেশক: এখানে, ওখানে, ঐখানে।",example:"স্থান নির্দেশক সর্বনাম।"),
    GrammarItem(pattern:"[N] は [Place] です",explanation:"কোনো কিছু কোথায় আছে তা বলতে।",example:"おてあらい は あそこ です (টয়লেট ঐখানে।)"),
    GrammarItem(pattern:"どこ / どちら",explanation:"স্থান বা দিক জিজ্ঞেস করতে ব্যবহৃত হয়।",example:"প্রশ্নবোধক স্থান নির্দেশক।"),
  ],
  4: [
    GrammarItem(pattern:"今 ～時 ～分 です",explanation:"বর্তমান সময় বলতে ব্যবহৃত হয়।",example:"いま ７じ １０ぷん です (এখন ৭টা ১০ বাজে।)"),
    GrammarItem(pattern:"V-ます / V-ません",explanation:"বর্তমান বা ভবিষ্যৎ কাজের ধরণ।",example:"あした はたらきます (আগামীকাল কাজ করব।)"),
    GrammarItem(pattern:"いま [Time] じ [Minute] ふん です",explanation:"সময় বলার নিয়ম। (যেমন: ４じ ５０ふん)",example:"সময় বলার ফরম্যাট।"),
    GrammarItem(pattern:"Verb ます / ました / ません / ませんでした",explanation:"বর্তমান(+) / অতীত(+) / বর্তমান(-) / অতীত(-)।",example:"べんきょうしました (পড়েছিলাম)"),
    GrammarItem(pattern:"[N (Time)] に [Verb]",explanation:"নির্দিষ্ট সময়ে কোনো কাজ করলে 'に' (ni) বসে।",example:"６じ に おきます (৬ টায় উঠি।)"),
    GrammarItem(pattern:"[N1] から [N2] まで",explanation:"থেকে... পর্যন্ত।",example:"সময়ের ব্যাপ্তি।"),
  ],
  5: [
    GrammarItem(pattern:"N (Place) へ いきます",explanation:"কোনো স্থানের দিকে যাওয়া বোঝাতে 'へ' পার্টিকেল বসে।",example:"きょうと へ いきます (কিয়োটো যাব।)"),
    GrammarItem(pattern:"いつ",explanation:"সময় জিজ্ঞাসা করতে (কবে/কখন)।",example:"いつ にほん へ いきますか (কবে জাপান যাবেন?)"),
    GrammarItem(pattern:"[Place] へ いきます / きます / かえります",explanation:"কোথাও যাওয়া (Go), আসা (Come) বা ফেরা (Return)। 'へ' (e) দিক বোঝায়।",example:"দিক নির্দেশক কণা।"),
    GrammarItem(pattern:"どこ [へ] も いきません",explanation:"কোথাও যাবো না (সম্পূর্ণ নেতিবাচক)।",example:"পূর্ণ নেতিবাচক।"),
    GrammarItem(pattern:"[Vehicle] で いきます",explanation:"'দে' (で) কণা দিয়ে যানবাহনের মাধ্যম বোঝায়। (বাসে/ট্রেনে)।",example:"যাতায়াতের মাধ্যম।"),
    GrammarItem(pattern:"[Person] と [Verb]",explanation:"'と' (to) মানে 'সাথে'। কারও সাথে কিছু করা।",example:"সঙ্গী বোঝাতে।"),
  ],
  6: [
    GrammarItem(pattern:"[N] を [Verb (Transitive)]",explanation:"'কে' বা 'টি' (Object marker)।",example:"ジュース を のみます (জুস পান করি।)"),
    GrammarItem(pattern:"[Place] で [Verb]",explanation:"কোনো স্থানে কাজ সম্পন্ন করা বোঝালে 'で' বসে।",example:"ক্রিয়া সম্পাদনের স্থান।"),
    GrammarItem(pattern:"いっしょに [Verb] ませんか",explanation:"'একসাথে কি (কাজটি) করবেন?' (কাউকে দাওয়াত দেওয়া)।",example:"প্রস্তাব দেওয়া।"),
  ],
  7: [
    GrammarItem(pattern:"[Tool/Language] で [Verb]",explanation:"মাধ্যম।",example:"はし で たべます (চপস্টিক দিয়ে খাই।)"),
    GrammarItem(pattern:"[Person] に [N] を あげます / かします",explanation:"কাউকে কিছু দেওয়া (Age-masu) বা ধার দেওয়া।",example:"প্রদান করা।"),
    GrammarItem(pattern:"[Person] に [N] を もらいます / かりる",explanation:"কারও থেকে কিছু নেওয়া (Morai-masu) বা ধার নেওয়া।",example:"গ্রহণ করা।"),
  ],
  8: [
    GrammarItem(pattern:"い-Adjective (যেমন: あつい - গরম)",explanation:"সরাসরি Noun এর আগে বসে। নেতিবাচক করতে 'い' বাদ দিয়ে 'くない' বসে।",example:"বিশেষণ প্রয়োগ।"),
    GrammarItem(pattern:"な-Adjective (যেমন: しずか - শান্ত)",explanation:"Noun এর আগে 'な' বসে। (しずかな まち - শান্ত শহর)।",example:"বিশেষণ প্রয়োগ।"),
    GrammarItem(pattern:"とても (খুব) / あまり (তেমন না)",explanation:"তীব্রতা বা দুর্বলতা বোঝাতে।",example:"মাত্রাসূচক শব্দ।"),
  ],
  9: [
    GrammarItem(pattern:"[N] が すきです / きらいです",explanation:"পছন্দ/অপছন্দ। এখানে 'কে' এর বদলে 'が' (ga) বসে।",example:"পছন্দ-অপছন্দ প্রকাশ।"),
    GrammarItem(pattern:"[N] が あります / わかります",explanation:"থাকা বা বুঝতে পারা।",example:"উপলব্ধি ও অস্তিত্ব।"),
    GrammarItem(pattern:"から (কারণ)",explanation:"বাক্যের শেষে কারণ দর্শাতে।",example:"কারণ সংযোগ।"),
  ],
  10: [
    GrammarItem(pattern:"[Place] に [Noun] が あります / います",explanation:"কোনো স্থানে কিছু আছে। (あります: বস্তু/গাছপালা; います: মানুষ/প্রাণী)",example:"অস্তিত্ব প্রকাশ।"),
    GrammarItem(pattern:"[N1 (Thing/Person)] は [Place] に あります / います",explanation:"নির্দিষ্ট ব্যক্তি বা বস্তু কোথায় আছে তা বলা।",example:"অবস্থান জানানো।"),
  ],
  11: [
    GrammarItem(pattern:"[Noun] が [Counter] あります/います",explanation:"সংখ্যার পরে 'কে', 'টি', 'জন' বোঝাতে কাউন্টার বসে।",example:"りんご を ひとつ たべました (১টি আপেল খেয়েছি।)"),
    GrammarItem(pattern:"[Time Period] に [Frequency] [Verb]",explanation:"নির্দিষ্ট সময়ে কতবার কাজ করা হয়।",example:"１しゅうかん に ２かい えいが を みます (১ সপ্তাহে ২ বার সিনেমা দেখি।)"),
    GrammarItem(pattern:"[Time/Money] くらい/ぐらい",explanation:"'প্রায়' বা 'কাছাকাছি' বোঝাতে।",example:"আনুমানিক পরিমাণ।"),
  ],
  12: [
    GrammarItem(pattern:"[Noun] は [Noun] より [Adj] です",explanation:"তুলনা করা (Comparison)। (N1, N2 এর চেয়ে...)",example:"তুলনামূলক বাক্য।"),
    GrammarItem(pattern:"[N1] と [N2] と どちらが [Adj] ですか",explanation:"দুটির মধ্যে কোনটি বেশি? উত্তর দিতে: [N] の ほうが [Adj] です।",example:"নির্বাচনমূলক প্রশ্ন।"),
    GrammarItem(pattern:"Past of い-Adj: 'い' বাদ দিয়ে 'かったです'",explanation:"বিশেষণের অতীত রূপ। (例: あつい → あつかったです - গরম ছিল)",example:"বিশেষণের অতীত।"),
    GrammarItem(pattern:"Past of な-Adj: শেষে 'でした'",explanation:"বিশেষণের অতীত রূপ। (例: しずか → しずか でした - শান্ত ছিল)",example:"বিশেষণের অতীত।"),
  ],
  13: [
    GrammarItem(pattern:"[Noun] が ほしい です",explanation:"কোনো বস্তু 'চাই' বা পাওয়ার ইচ্ছা। (বই চাই, গাড়ি চাই)",example:"আকাঙ্ক্ষা প্রকাশ।"),
    GrammarItem(pattern:"[Verb (Masu form)] + たい です",explanation:"কোনো কাজ 'করতে চাই'। (たべます → たべたい - খেতে চাই)",example:"কাজ করার ইচ্ছা।"),
    GrammarItem(pattern:"[Place] へ [Verb (Masu form)] に いきます",explanation:"কোনো উদ্দেশ্যে কোথাও যাওয়া।",example:"デパート へ かいもの に いきます (কেনাকাটা করতে যাচ্ছি।)"),
  ],
  14: [
    GrammarItem(pattern:"[Verb て-form] ください",explanation:"'দয়া করে (কাজটি) করুন।'",example:"অনুরোধ।"),
    GrammarItem(pattern:"[Verb て-form] います",explanation:"বর্তমানে কোনো কাজ 'চলছে' (Present Continuous)।",example:"চলমান ক্রিয়া।"),
  ],
  15: [
    GrammarItem(pattern:"[Verb て-form] も いい です か",explanation:"'আমি কি (কাজটি) করতে পারি?' (অনুমতি চাওয়া)",example:"অনুমতি প্রার্থনা।"),
    GrammarItem(pattern:"[Verb て-form] は いけません",explanation:"'করা যাবে না' (নিষেধাজ্ঞা)",example:"ここ で しゃしん を とって は いけません (এখানে ছবি তোলা নিষেধ।)"),
  ],
  16: [
    GrammarItem(pattern:"V1-te, V2-te, [V3]",explanation:"একের পর এক কাজ করা। (সকালে উঠে, নাস্তা করে, অফিসে যাই)",example:"ধারাবাহিক ক্রিয়া।"),
    GrammarItem(pattern:"[い-Adj] くて / [な-Adj] で",explanation:"দুটি বিশেষণকে জোড়া দেওয়া। (সস্তা এবং সুস্বাদু: やすくて、おいしい)",example:"বিশেষণ সংযোগ।"),
    GrammarItem(pattern:"[V て-form] から、[Verb]",explanation:"একটি কাজ শেষ করার 'পর' অন্য কাজ করা।",example:"কাজ সমাপ্তির পর।"),
  ],
  17: [
    GrammarItem(pattern:"Nai-form Transformation",explanation:"Group 1: 'i' সাউন্ডকে 'a' সাউন্ড করে 'ない' যোগ। (かきます → かかない)",example:"নাই-ফর্ম রূপান্তর।"),
    GrammarItem(pattern:"[Verb ない-form] で ください",explanation:"'দয়া করে করবেন না।'",example:"নিষেধ অনুরোধ।"),
    GrammarItem(pattern:"[Verb ない-form] なければ なりません",explanation:"'অবশ্যই করতে হবে' (Must do)",example:"বাধ্যবাধকতা।"),
    GrammarItem(pattern:"[Verb ない-form] なくても いい です",explanation:"'না করলেও চলবে' (Don't have to)",example:"প্রয়োজনহীনতা।"),
  ],
  18: [
    GrammarItem(pattern:"Dictionary Form (মূল রূপ)",explanation:"ডিকশনারিতে ভার্ব খুঁজে পাওয়ার রূপ। (Group 1: 'u' সাউন্ড দিয়ে শেষ হয়)",example:"মূল ক্রিয়ার রূপ।"),
    GrammarItem(pattern:"[V-Dictionary Form] こと が できます",explanation:"'আমি (কাজটি) করতে পারি/সক্ষম।'",example:"সক্ষমতা প্রকাশ।"),
    GrammarItem(pattern:"[V-Dictionary Form] まえに",explanation:"'(কাজটি) করার আগে।'",example:"পূর্ববর্তী কাজ।"),
  ],
  19: [
    GrammarItem(pattern:"Ta-form (অতীত রূপ)",explanation:"ঠিক 'Te-form' এর মতো, শুধু 'te' এর জায়গায় 'ta' বসে।",example:"অতীত ক্রিয়া রূপান্তর।"),
    GrammarItem(pattern:"[Verb た-form] こと が あります",explanation:"'আমার (কাজটি) করার অভিজ্ঞতা আছে।' (যেমন: জাপান যাওয়ার অভিজ্ঞতা)",example:"অভিজ্ঞতা প্রকাশ।"),
    GrammarItem(pattern:"[V-ta] り、[V-ta] り します",explanation:"বিভিন্ন কাজের তালিকা দেওয়া (এটা করি, ওটা করি ইত্যাদি)",example:"কাজের তালিকা।"),
  ],
  20: [
    GrammarItem(pattern:"Plain vs Polite Form",explanation:"বন্ধুবান্ধব বা পরিবারের সাথে কথা বলতে 'ます' এর বদলে 'Dictionary/Nai/Ta' ফর্ম ব্যবহার করা।",example:"たべます (Polite) → たべる (Plain)"),
  ],
  21: [
    GrammarItem(pattern:"[Plain Form] と おもいます",explanation:"'আমি মনে করি যে...'। আপনার নিজস্ব মতামত প্রকাশ করতে ব্যবহৃত হয়।",example:"あした は あめ が ふる と おもいます (আগামীকাল বৃষ্টি হবে মনে করি।)"),
    GrammarItem(pattern:"[Sentence] と いいました",explanation:"'তিনি বলেছিলেন যে...'। কারো কথা উদ্ধৃত করতে ব্যবহৃত হয়।",example:"উদ্ধৃতি।"),
    GrammarItem(pattern:"[Verb/Adj Plain Form] でしょう？",explanation:"'...তাই না?'। যখন আপনি শ্রোতার কাছ থেকে নিশ্চয়তা বা সমর্থন আশা করেন।",example:"নিশ্চয়তা চাওয়া।"),
  ],
  22: [
    GrammarItem(pattern:"[Verb Plain Form] + Noun",explanation:"জাপানিতে একটি পুরো বাক্য দিয়ে একটি Noun-কে বর্ণনা করা যায়। বাংলায় এটি 'যে/যা' দিয়ে কাজ করে।",example:"わたし が かった ほん (আমার কেনা বইটি।)"),
    GrammarItem(pattern:"[Modified Noun] は [Adj/Noun] です",explanation:"বিশেষিত Noun-টি বাক্যের সাবজেক্ট হিসেবে কাজ করে।",example:"わたし が すんでいる まち は しずか です (আমি যে শহরে থাকি সেটি শান্ত।)"),
  ],
  23: [
    GrammarItem(pattern:"[V-Dictionary/Nai/Ta/Adj] とき、[Sentence]",explanation:"'যখন (কাজটি হয়/হয়েছিল)... তখন...'",example:"ねるとき、「おやすみなさい」と いいます (শোবার সময় শুভরাত্রি বলি।)"),
    GrammarItem(pattern:"[V-Dictionary Form] と、[Sentence]",explanation:"'যদি (এটি হয়), তবে (স্বাভাবিকভাবেই এটি ঘটবে)'। এটি প্রাকৃতিক নিয়ম বা যন্ত্রের কাজ বোঝাতে ব্যবহৃত হয়।",example:"ボタン を おす と、おつり が でます (বোতাম চাপলে টাকা বের হয়।)"),
  ],
  24: [
    GrammarItem(pattern:"[Person] は [わたし] に [Noun] を くれます",explanation:"কেউ 'আমাকে' বা আমার পরিবারের কাউকে কিছু দিলে 'くれます' (Kuremasu) বসে।",example:"প্রদান করা (আমাকে)।"),
    GrammarItem(pattern:"[Verb て-form] あげます",explanation:"কারো জন্য কোনো কাজ (উপকার) করে দেওয়া।",example:"উপকার করা।"),
    GrammarItem(pattern:"[Verb て-form] もらいます",explanation:"কারো কাছ থেকে কোনো কাজ (উপকার) করিয়ে নেওয়া।",example:"উপকার গ্রহণ।"),
    GrammarItem(pattern:"[Verb て-form] くれます",explanation:"কেউ দয়া করে আমার জন্য কোনো কাজ করে দিলে।",example:"উপকার করা (আমাকে)।"),
  ],
  25: [
    GrammarItem(pattern:"[Verb た-form] + ら、[Sentence]",explanation:"'যদি... তবে...'। এটি সবচেয়ে বেশি ব্যবহৃত 'If' কন্ডিশন।",example:"おかね が あったら、りょこう します (টাকা থাকলে ভ্রমণ করব।)"),
    GrammarItem(pattern:"[Verb て-form] も、[Sentence]",explanation:"'যদিও... তবুও...' (Even if)",example:"あめ が ふっても、いきます (বৃষ্টি হলেও যাবো।)"),
  ],
};
